import React, { useEffect, useRef, useState } from 'react';
import { api, ApiError } from '@storeloop/api-client';
import { displayTime, formatRate, homeFor, payloadKey, statusLabel, validatePhotos, filterParams } from './policy';
import { Badge, Empty, ErrorBox, Field, Link, Load, Notice, Pager, ScopeExplorer, Table, backLink, choices, detailLink, go, pageQuery, queryString, useAction, useData, useLocation, useOptions, useSession, type Page, type Row } from './ui';
export type PickedPhoto = {
    id: string;
    file: File;
    url: string;
};
export function PhotoPicker({ photos, onChange, max = 5 }: {
    photos: PickedPhoto[];
    onChange: (photos: PickedPhoto[]) => void;
    max?: number;
}) { const [error, setError] = useState(''); const latest = useRef(photos); latest.current = photos; useEffect(() => () => latest.current.forEach(p => URL.revokeObjectURL(p.url)), []); const input = React.useId(); return <section className="photo-picker"><label htmlFor={input}>사진 선택 · JPEG/PNG, 장당 10MiB, 최대 {max}장</label><input id={input} type="file" accept="image/jpeg,image/png" multiple={max > 1} onChange={e => { const files = Array.from(e.target.files ?? []); const next = max === 1 ? files : [...photos.map(p => p.file), ...files]; const issue = validatePhotos(next, max); setError(issue); if (!issue) {
    if (max === 1)
        photos.forEach(p => URL.revokeObjectURL(p.url));
    onChange([...(max === 1 ? [] : photos), ...files.map(file => ({ id: crypto.randomUUID(), file, url: URL.createObjectURL(file) }))]);
} e.target.value = ''; }}/>{error && <p role="alert">{error}</p>}<div className="photo-preview">{photos.map((p, i) => <figure key={p.id}><img src={p.url} alt={`선택 사진 ${i + 1}: ${p.file.name}`}/><figcaption>사진 {i + 1} · {p.file.name}<br />{(p.file.size / 1024).toFixed(0)} KiB</figcaption><div className="actions"><button type="button" disabled={i === 0} onClick={() => { const next = [...photos]; [next[i - 1], next[i]] = [next[i], next[i - 1]]; onChange(next); }}>사진 {i + 1} 앞으로</button><button type="button" onClick={() => { URL.revokeObjectURL(p.url); onChange(photos.filter(x => x.id !== p.id)); }}>사진 {i + 1} 삭제</button></div></figure>)}</div></section>; }
export function Photo({ photo, label }: {
    photo: Row;
    label: string;
}) { const [broken, setBroken] = useState(false), [revision, setRevision] = useState(0); if (broken)
    return <Notice>사진을 불러오지 못했습니다. <button onClick={() => { setRevision(x => x + 1); setBroken(false); }}>사진 다시 보기</button></Notice>; const src = photo.url ?? `/api/media/${photo.media_id ?? photo.photo_id ?? photo.id}`; return <figure id={`photo-${photo.position}`}><img key={revision} src={src} alt={label} onError={() => setBroken(true)}/><figcaption>{label}{photo.source_kind === 'ai_generated_demo' && <span className="badge">AI 생성 시연 이미지</span>}</figcaption></figure>; }
export function SubmissionList({ heading = '제출 이력 탐색' }: {
    heading?: string;
}) { const { account } = useSession(); const p = new URLSearchParams(useLocation().split('?')[1]); const query = useData<Page<Row>>('/submissions' + pageQuery({ status: p.get('status'), needs_ofc_review: p.get('needs_ofc_review') })); const root = homeFor(account.role); return <ScopeExplorer title={heading}><div className="title-row"><div><p className="eyebrow">HISTORY EXPLORER</p><h1>{heading}</h1></div>{account.role === 'store_owner' && <Link className="button primary" to={root + '/submit'}>사진으로 점검하기</Link>}</div><p>매장과 기간을 좁혀 결과를 확인하고, 같은 매대의 변화로 이어가세요.</p><form className="inline-form" onSubmit={e => { e.preventDefault(); const form = new FormData(e.currentTarget); const params = filterParams(window.location.search); const status = String(form.get('status')); if (status)
    params.set('status', status); go(window.location.pathname + '?' + params.toString()); }}><label>처리 상태 <select name="status" defaultValue={p.get('status') ?? ''}><option value="">전체</option>{['queued', 'running', 'succeeded', 'failed'].map(s => <option key={s} value={s}>{statusLabel(s)}</option>)}</select></label><button>상태 적용</button></form><Load query={query}>{(data: Page<Row>) => <>{!data.items.length ? <Empty>선택한 기간에 제출한 사진이 없습니다. 미제출은 미준수로 계산하지 않습니다.</Empty> : <div className="records">{data.items.map(s => <article className="record" key={s.id}>{s.thumbnail && <img src={s.thumbnail.thumbnail_url ?? s.thumbnail.url} alt={`${s.category_name} 제출 사진 썸네일`}/>}<div><small>{s.store_name} / {displayTime(s.created_at)}</small><h2><Link to={detailLink(root + '/submissions/' + s.id)}>{s.category_name} 점검 결과</Link></h2><Badge value={s.job.status}/>{s.source_kind === 'ai_generated_demo' && <span className="badge">AI 생성 시연 이미지</span>}{s.review_summary?.source_kind === 'mock' && <span className="badge">Mock 데이터</span>}</div><dl><div><dt>준수율</dt><dd>{formatRate(s.review_summary?.compliance_rate)}</dd></div><div><dt>판단 가능률</dt><dd>{formatRate(s.review_summary?.assessable_rate)}</dd></div></dl><div className="record-action">{s.parent_submission_id && <Link to={root + '/submissions/' + s.id + '/compare' + window.location.search}>이전·이후 비교 →</Link>}<small>사진 {s.photo_count}장 · 미해결 {s.open_issue_count}건</small></div></article>)}</div>}<Pager data={data}/></>}</Load></ScopeExplorer>; }
export function Inquiry({ submissionId }: {
    submissionId: string;
}) { const [title, setTitle] = useState(''), [description, setDescription] = useState(''); const key = useRef(payloadKey()).current; const action = useAction(); return <form className="panel" onSubmit={async (e) => { e.preventDefault(); const body = { submission_id: submissionId, title, description, priority: 'normal' }; await action.run(async () => { const issue = await api.post<Row>('/issues', body, key(body)); go(homeFor((await api.me()).role) + '/issues/' + issue.id); }, '확인 요청을 접수했습니다.'); }}><h2>OFC에 확인 요청</h2><Field label="문의 제목" name="title" value={title} onChange={setTitle} required maxLength={160}/><Field label="확인할 내용" name="description" type="textarea" value={description} onChange={setDescription} required maxLength={2000}/>{action.feedback}<button className="primary" disabled={action.busy}>OFC에 확인 요청</button></form>; }
export function SubmissionDetail({ id }: {
    id: string;
}) { const query = useData<Row>('/submissions/' + id, true); const { account } = useSession(); const root = homeFor(account.role); const own = account.role === 'store_owner'; return <div className="detail-workspace"><Link to={backLink(root + '/submissions')}>← 탐색 결과로</Link><Load query={query}>{(s: Row) => <><div className="title-row"><div><p className="eyebrow">{s.store_name} / {displayTime(s.created_at)}</p><h1>{s.category_name} 점검 결과</h1></div><Badge value={s.job.status}/></div>{s.source_kind === 'ai_generated_demo' && <p className="badge">AI 생성 시연 이미지</p>}<AnalysisState job={s.job} refresh={query.refresh}/><div className="detail-grid"><section><h2>제출 사진과 질문</h2><p className="quote">{s.question || '별도 질문 없이 제출한 사진입니다.'}</p><div className="submitted-photos">{s.photos.map((p: Row) => <Photo key={p.id} photo={p} label={`${s.category_name} 제출 사진 ${p.position} · ${displayTime(s.created_at)}`}/>)}</div><details className="panel"><summary>제출 당시 적용 기준 · {s.context.guidelines.length}개</summary>{s.context.guidelines.length ? s.context.guidelines.map((g: Row) => <article key={g.version_id}><h3>{g.rule_key} · {g.level} · v{g.version}</h3><p>{g.text}</p></article>) : <p>적용할 기준이 없어 OFC 확인이 필요해요.</p>}<h3>비교 Reference</h3>{s.context.references.length ? s.context.references.map((r: Row) => <div key={r.reference_id}><Photo photo={(s.reference_photos ?? []).find((item: Row) => item.reference_id === r.reference_id)?.photo ?? { photo_id: r.photo_id, position: r.position }} label={`Reference ${r.position} · ${r.caption}`}/></div>) : <p>비교 Reference가 없습니다.</p>}</details></section><section>{s.review ? <Review review={s.review}/> : <Empty>분석 결과가 저장되면 이곳에서 확인할 수 있습니다.</Empty>}<div className="actions">{own && s.submitted_by_id === account.id && <Link className="button primary" to={root + '/submit?parent=' + s.id}>개선 후 다시 제출</Link>}{s.parent && <Link className="button" to={root + '/submissions/' + s.id + '/compare' + window.location.search}>이전·이후 비교</Link>}</div><section className="panel"><h2>연결된 이력</h2>{s.parent && <p><Link to={root + '/submissions/' + s.parent.id}>이전 제출 · {displayTime(s.parent.created_at)}</Link></p>}{s.children.map((c: Row) => <p key={c.id}><Link to={root + '/submissions/' + c.id}>후속 제출 · {displayTime(c.created_at)}</Link></p>)}{s.issues.map((issue: Row) => <p key={issue.id}><Link to={root + '/issues/' + issue.id}>{issue.title}</Link> <Badge value={issue.status}/></p>)}{!s.parent && !s.children.length && !s.issues.length && <p>연결된 후속 이력이 없습니다.</p>}</section>{(!own || s.submitted_by_id === account.id) && <Inquiry submissionId={id}/>}</section></div></>}</Load></div>; }
function AnalysisState({ job, refresh }: {
    job: Row;
    refresh: () => void;
}) { const [, tick] = useState(0); useEffect(() => { if (['succeeded', 'failed'].includes(job.status))
    return; const t = setInterval(() => tick(x => x + 1), 1000); return () => clearInterval(t); }, [job.status]); if (job.status === 'succeeded')
    return <p role="status" className="notice success">분석 완료 · 결과를 확인해 주세요.</p>; if (job.status === 'failed')
    return <Notice tone="error"><h2>분석을 완료하지 못했어요</h2><p>{job.error_message} ({job.error_code})</p><p>기술 실패는 평가 점수로 계산하지 않습니다. 운영자에게 복구를 요청할 수 있습니다.</p><button onClick={refresh}>상태를 다시 확인</button></Notice>; const elapsed = Math.max(Math.floor((Date.now() - new Date(job.queued_at).getTime()) / 1000), Math.floor(job.elapsed_ms / 1000)); return <section className="notice" aria-label="분석 진행 상태"><h2>{job.status === 'queued' ? '분석 대기 중' : '사진을 분석하고 있어요'}</h2><p>{elapsed}초 경과</p>{(job.delayed || elapsed > 30) && <p role="status">분석에 시간이 더 필요해요. 이 화면을 나가도 이력에서 확인할 수 있어요.</p>}<button onClick={refresh}>상태를 다시 확인</button></section>; }
export function Review({ review }: {
    review: Row;
}) { const r = review.result; return <section className="review"><p className="eyebrow">{review.source_kind === 'real_ai' ? '실제 AI 분석' : 'Mock 데이터'}</p><h2>평가와 개선 제안</h2><div className="rates"><div><span>준수율</span><strong>{formatRate(review.compliance_rate)}</strong></div><div><span>판단 가능률</span><strong>{formatRate(review.assessable_rate)}</strong></div><div><span>판단 가능한 기준</span><strong>{review.pass_count + review.fail_count}/{review.pass_count + review.fail_count + review.unknown_count}</strong></div></div>{review.compliance_rate == null && <p>판단 가능한 기준이 없어 준수율을 계산할 수 없습니다.</p>}<h3>질문에 대한 답변</h3><p>{r.question_answer}</p><p>{r.summary}</p><p>모델 신뢰도: {{ high: '높음', medium: '보통', low: '낮음' }[r.overall_confidence as string] ?? r.overall_confidence}</p>{review.needs_ofc_review && <Notice>OFC 확인이 필요합니다. 아래 확인 요청에서 추가 의견을 남겨 주세요.</Notice>}<div className="criteria">{r.criteria.map((c: Row) => <article className="criterion" key={c.version_id}><div className="title-row"><h3>{c.rule_key} · v{c.version}</h3><Badge value={c.verdict}/></div><p>{c.reason}</p><ul>{c.evidence.map((e: Row, i: number) => <li key={i}><a href={'#photo-' + e.photo_position}>사진 {e.photo_position}</a> · {e.observation}</li>)}</ul>{c.actions.length > 0 && <><h4>개선 행동</h4><ul>{c.actions.map((a: string, i: number) => <li key={i}>{a}</li>)}</ul></>}</article>)}</div><h3>Reference 비교</h3>{r.reference_comparisons.length ? r.reference_comparisons.map((c: Row) => <p key={c.reference_id}><Badge value={c.verdict}/> 사진 {c.photo_positions.join(', ')} · {c.observation}</p>) : <p>비교 Reference가 없습니다.</p>}{r.limitations.length > 0 && <Notice><strong>판단의 한계</strong><ul>{r.limitations.map((l: string, i: number) => <li key={i}>{l}</li>)}</ul></Notice>}{r.follow_up_comparison && <p>{r.follow_up_comparison}</p>}</section>; }
export function Comparison({ id }: {
    id: string;
}) { const query = useData<Row>('/submissions/' + id + '/comparison'); const current = useData<Row>('/submissions/' + id); const parent = useData<Row>(current.data?.parent ? '/submissions/' + current.data.parent.id : null); const { account } = useSession(); const root = homeFor(account.role); const version = (resource: typeof parent, ruleKey: string) => { if (resource.error) return '조회 실패'; if (!resource.data) return '불러오는 중'; const criterion = resource.data.context.guidelines.find((g: Row) => g.rule_key === ruleKey); return criterion ? `v${criterion.version}` : '미적용'; }; return <div className="detail-workspace"><Link to={root + '/submissions/' + id + window.location.search}>← 현재 결과로</Link><h1>이전·이후 비교</h1><Load query={query}>{(d: Row) => <>{d.criteria.some((c: Row) => c.criterion_changed) && <Notice>적용 기준이 달라 단순 점수 비교에 주의가 필요합니다.</Notice>}<div className="compare-grid">{[{ side: d.parent, title: '이전 제출', metadata: parent }, { side: d.current, title: '개선 후 제출', metadata: current }].map(({ side, title, metadata }) => <section className="panel" key={title}><h2>{title}</h2>{side ? <><Load query={metadata}>{detail => <p>{displayTime(detail.created_at)}</p>}</Load><p>준수율 {formatRate(side.compliance_rate)} · 판단 가능률 {formatRate(side.assessable_rate)}</p>{side.photos.map((p: Row) => <Photo key={p.id} photo={p} label={`${title} 사진 ${p.position}`}/>)}<Link to={root + '/submissions/' + side.submission_id}>사진·기준·평가 전체 보기</Link></> : <Empty>비교할 이전 제출이 없습니다.</Empty>}</section>)}</div><Table caption="기준별 변화" head={['기준', '이전 기준 버전', '이전', '이후 기준 버전', '이후', '변화']}>{d.criteria.map((c: Row) => <tr key={c.rule_key}><th>{c.rule_key}{c.criterion_changed && ' · 기준 변경'}</th><td>{version(parent, c.rule_key)}</td><td>{c.before ? <Badge value={c.before}/> : '—'}</td><td>{version(current, c.rule_key)}</td><td>{c.after ? <Badge value={c.after}/> : '—'}</td><td>{{ resolved: '개선됨', regressed: '개선 필요', unchanged: '변화 없음', unavailable: '비교 불가' }[c.change as string]}</td></tr>)}</Table>{d.narrative && <p>{d.narrative}</p>}<p>기준 버전이 다르거나 판단 불가가 포함된 항목은 직접 비교하지 않습니다.</p></>}</Load></div>; }
export function Issues({ id }: {
    id?: string;
}) { const { account } = useSession(); const root = homeFor(account.role); const p = new URLSearchParams(useLocation().split('?')[1]); const query = useData(id ? '/issues/' + id : '/issues' + pageQuery({ status: p.get('status'), unresolved: p.get('unresolved') })); if (id)
    return <div className="detail-workspace"><Link to={backLink(root + '/issues')}>← 확인 이슈 탐색</Link><Load query={query}>{(data: Row) => <IssueDetail key={id} data={data} refresh={query.refresh}/>}</Load></div>; return <ScopeExplorer title="확인 이슈"><h1>확인 이슈 탐색</h1><form className="inline-form" onSubmit={e => { e.preventDefault(); const params = filterParams(window.location.search); const status = new FormData(e.currentTarget).get('status'); if (status)
    params.set('status', String(status)); go(window.location.pathname + '?' + params); }}><label>조치 상태 <select name="status" defaultValue={p.get('status') ?? ''}><option value="">전체</option>{['open', 'in_progress', 'resolved'].map(s => <option value={s} key={s}>{statusLabel(s)}</option>)}</select></label><button>상태 적용</button></form><Load query={query}>{(data: Page<Row>) => <>{!data.items.length ? <Empty /> : <div className="records">{data.items.map(i => <article className="record" key={i.id}><div><small>{i.store_name} / {i.category_name}</small><h2><Link to={detailLink(root + '/issues/' + i.id)}>{i.title}</Link></h2><span>{i.assignee_name ?? '담당 미배정'}</span></div><Badge value={i.status}/><span>{i.priority === 'high' ? '높은 우선순위' : '일반'}</span><small>{displayTime(i.updated_at)}</small></article>)}</div>}<Pager data={data}/></>}</Load></ScopeExplorer>; }
function IssueDetail({ data, refresh }: {
    data: Row;
    refresh: () => void;
}) { const { account } = useSession(); const editable = account.role !== 'store_owner'; const assignees = useData<Page<Row>>(editable ? '/issues/' + data.id + '/assignees?page=1&page_size=100' : null); const [draft, setDraft] = useState({ status: data.status, assignee_id: data.assignee_id ?? '', priority: data.priority, resolution: data.resolution ?? '', next_check_at: data.next_check_at ? new Date(new Date(data.next_check_at).getTime() - new Date(data.next_check_at).getTimezoneOffset() * 60000).toISOString().slice(0, 16) : '' }), [comment, setComment] = useState(''); const action = useAction(refresh); return <><h1>{data.title}</h1><p>{data.store_name} / {data.category_name} <Badge value={data.status}/></p><p>{data.description}</p><Link className="button" to={homeFor(account.role) + '/submissions/' + data.submission_id}>원본 사진·평가·기준 보기</Link>{data.resolution && <Notice>해결 내용: {data.resolution}</Notice>}{editable && <div className="compare-grid"><form className="panel" onSubmit={async (e) => { e.preventDefault(); await action.run(async () => { await api.patch('/issues/' + data.id, { version: data.version, ...draft, assignee_id: draft.assignee_id || null, next_check_at: draft.next_check_at ? new Date(draft.next_check_at).toISOString() : null }); refresh(); }); }}><h2>담당·조치 상태</h2><Field label="상태" name="status" value={draft.status} onChange={v => setDraft({ ...draft, status: v })} options={['open', 'in_progress', 'resolved'].map(value => ({ value, label: statusLabel(value) }))}/><Field label="담당자" name="assignee_id" value={draft.assignee_id} onChange={v => setDraft({ ...draft, assignee_id: v })} options={choices(assignees.data?.items, '미배정')}/><Field label="우선순위" name="priority" value={draft.priority} onChange={v => setDraft({ ...draft, priority: v })} options={[{ value: 'normal', label: '일반' }, { value: 'high', label: '높음' }]}/><Field label="다음 확인 시각 (현지 시각)" name="next_check_at" type="datetime-local" value={draft.next_check_at} onChange={v => setDraft({ ...draft, next_check_at: v })}/><Field label="해결 내용" name="resolution" type="textarea" value={draft.resolution} onChange={v => setDraft({ ...draft, resolution: v })} required={draft.status === 'resolved'} maxLength={2000}/>{action.feedback}<button className="primary" disabled={action.busy}>변경 저장</button></form><form className="panel" onSubmit={async (e) => { e.preventDefault(); if (await action.run(async () => { await api.post('/issues/' + data.id + '/actions', { body: comment }); refresh(); }, '조치 의견을 저장했습니다.'))
    setComment(''); }}><h2>조치 의견</h2><Field label="현장 조치와 확인 내용" name="body" value={comment} onChange={setComment} type="textarea" required maxLength={2000}/><button disabled={action.busy}>조치 의견 남기기</button></form></div>}<h2>조치 이력</h2>{data.actions.length ? <ol className="timeline">{data.actions.map((a: Row) => <li key={a.id}><strong>{a.actor_name}</strong> · {displayTime(a.created_at)}<p>{a.body}</p>{a.to_status && <Badge value={a.to_status}/>}</li>)}</ol> : <Empty>아직 조치 의견이 없습니다.</Empty>}</>; }
export function Notifications() { const { account } = useSession(); const query = useData<Page<Row> & {
    unread_count: number;
}>('/notifications' + pageQuery({}, false)); const action = useAction(); return <div className="detail-workspace"><h1>내 알림</h1><p>현재 접근 가능한 업무 알림만 표시합니다.</p>{action.feedback}<Load query={query}>{(d: Page<Row> & {
    unread_count: number;
}) => <><p>읽지 않은 알림 {d.unread_count}건</p>{d.items.length ? d.items.map(n => <article className="record" key={n.id}><div><h2>{n.title}</h2><small>{displayTime(n.created_at)} · {n.read_at ? '읽음' : '새 알림'}</small></div><button disabled={action.busy} onClick={() => action.run(async () => { await api.post('/notifications/' + n.id + '/read'); query.refresh(); go(homeFor(account.role) + (n.target.type === 'issue' ? '/issues/' : '/submissions/') + n.target.id); }, '알림을 읽었습니다.')}>대상 확인</button></article>) : <Empty />}<Pager data={d}/></>}</Load></div>; }
