import React from 'react';
import {afterEach,it,expect,vi} from 'vitest';
import {cleanup,render,screen,fireEvent,waitFor} from '@testing-library/react';
import {QueryClientProvider} from '@tanstack/react-query';
import {MemoryRouter} from 'react-router-dom';
import {api,ApiError,type AccountMe} from '@storeloop/api-client';
import {App} from '../src/app/App';
import {createAppQueryClient} from '../src/app/query-client';
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();});

it('실제 App의 CSRF 오류는 업무캐시·사진·질문을 보존하고 동일키의 명시 재시도만 허용한다',async()=>{
 const account:AccountMe={id:'csrf-owner',login_id:'csrf.owner',display_name:'CSRF 검수 점주',role:'store_owner',region_id:null,is_active:true,version:1,store_ids:['store'],permissions:['submit']};
 const page=(items:unknown[])=>({items,total:items.length,page:1,page_size:100});
 vi.spyOn(api,'me').mockResolvedValue(account);
 vi.spyOn(api,'get').mockImplementation(async(path:string)=>path.startsWith('/stores')?page([{id:'store',name:'합성 매장',is_active:true}]):path.startsWith('/categories')?page([{id:'category',name:'음료',is_active:true}]):page([]));
 const upload=vi.spyOn(api,'upload').mockRejectedValue(new ApiError(403,'CSRF_INVALID','인증 확인값 변경'));
 URL.createObjectURL=vi.fn(()=> 'blob:csrf-preview');URL.revokeObjectURL=vi.fn();
 const client=createAppQueryClient();
 const removed=vi.fn();client.getQueryCache().subscribe(event=>{if(event.type==='removed'&&event.query.queryKey[0]==='/stores?is_active=true&page_size=100')removed();});
 render(<QueryClientProvider client={client}><MemoryRouter initialEntries={['/store-owner/submit']}><App/></MemoryRouter></QueryClientProvider>);
 await screen.findByRole('option',{name:'합성 매장'});
 fireEvent.change(screen.getByLabelText('카테고리 (필수)'),{target:{value:'category'}});
 const file=new File(['synthetic'],'csrf-photo.png',{type:'image/png'});
 fireEvent.change(screen.getByLabelText(/매대 사진 \(필수/),{target:{files:[file]}});
 fireEvent.change(screen.getByLabelText(/궁금한 점/),{target:{value:'보존할 점주 질문'}});
 fireEvent.submit(screen.getByRole('button',{name:'사진 접수하고 분석 시작'}).closest('form')!);
 await waitFor(()=>expect(upload).toHaveBeenCalledTimes(1));
 await screen.findByRole('alert');
 expect(removed).not.toHaveBeenCalled();
 expect(client.getQueryData(['/stores?is_active=true&page_size=100'])).toBeTruthy();
 expect(screen.getByText('보안 확인이 만료되었습니다. 입력은 유지했으니 다시 시도해 주세요.')).toBeTruthy();
 expect(screen.queryByText('현재 권한으로 접근할 수 없습니다.')).toBeNull();
 expect((screen.getByLabelText(/궁금한 점/) as HTMLTextAreaElement).value).toBe('보존할 점주 질문');
 expect(screen.getByAltText('선택한 사진 1').getAttribute('src')).toBe('blob:csrf-preview');
 expect(upload).toHaveBeenCalledTimes(1);
 fireEvent.submit(screen.getByRole('button',{name:'사진 접수하고 분석 시작'}).closest('form')!);
 await waitFor(()=>expect(upload).toHaveBeenCalledTimes(2));
 expect(upload.mock.calls[1][3]).toBe(upload.mock.calls[0][3]);
 expect(upload.mock.calls[1][2][0].file).toBe(file);
 client.clear();
});
