import React, { useRef, useState } from 'react';
import { payloadKey, validatePhotos } from '../shared/policy';
import { PhotoPicker, type PickedPhoto, SubmissionList, SubmissionDetail, Comparison, Issues, Notifications } from '../shared/business';
import { api, ErrorBox, Field, Link, Load, Notice, choices, go, useAction, useData, useOptions, type Row } from '../shared/ui';
function Submit() { const params = new URLSearchParams(window.location.search); const parentId = params.get('parent'); const parent = useData<Row>(parentId ? '/submissions/' + parentId : null); const { stores, categories } = useOptions(); const [draft, setDraft] = useState({ store_id: params.get('store_id') ?? '', category_id: params.get('category_id') ?? '', question: '' }); const [photos, setPhotos] = useState<PickedPhoto[]>([]), [validation, setValidation] = useState(''); const key = useRef(payloadKey()).current; const action = useAction(() => { stores.refresh(); categories.refresh(); }); const storeId = parent.data?.store_id ?? draft.store_id, categoryId = parent.data?.category_id ?? draft.category_id; return <div className="detail-workspace narrow"><Link to="/store-owner">← 이력 탐색으로</Link><p className="eyebrow">NEW OBSERVATION</p><h1>{parentId ? '개선 후 다시 제출' : '사진으로 점검하기'}</h1><p>매대 전체와 앞줄이 선명하게 보이는 사진을 선택해 주세요.</p><ErrorBox error={stores.error} retry={stores.refresh}/><ErrorBox error={categories.error} retry={categories.refresh}/>{parentId && <Load query={parent}>{(p: Row) => <Notice><strong>이전 제출: {p.store_name} / {p.category_name}</strong><p>새 사진은 이 결과와 연결됩니다. 이전 평가와 기준은 보존됩니다.</p><ul>{p.review?.result.criteria.filter((c: Row) => c.verdict !== 'pass').map((c: Row) => <li key={c.rule_key}>{c.rule_key}: {c.reason}</li>)}</ul></Notice>}</Load>}{stores.data && !stores.data.items.some(s => s.can_submit) && <Notice>제출 가능한 연결 매장이 없습니다. 운영자에게 연결 상태를 확인해 주세요.</Notice>}<form className="panel" onSubmit={async (e) => { e.preventDefault(); const error = validatePhotos(photos.map(p => p.file)); setValidation(error); if (error)
    return; const metadata = { store_id: storeId, category_id: categoryId, question: draft.question, parent_submission_id: parentId }; await action.run(async () => { const result = await api.upload<Row>('/submissions', metadata, photos.map(p => ({ field: 'photos', file: p.file })), key(metadata, photos.map(p => p.id))); go('/store-owner/submissions/' + result.submission_id); }, '사진을 접수했습니다.'); }}><div className="form-grid"><Field label="매장" name="store_id" value={storeId} onChange={v => setDraft({ ...draft, store_id: v })} options={choices(stores.data?.items.filter(s => s.can_submit), '매장 선택')} disabled={!!parentId} required/><Field label="카테고리" name="category_id" value={categoryId} onChange={v => setDraft({ ...draft, category_id: v })} options={choices(categories.data?.items.filter(c => c.is_active), '카테고리 선택')} disabled={!!parentId} required/></div><PhotoPicker photos={photos} onChange={setPhotos}/><Field label="질문 또는 현장 상황" name="question" value={draft.question} onChange={v => setDraft({ ...draft, question: v })} type="textarea" maxLength={2000}><span>{draft.question.length}/2000자</span></Field>{validation && <p role="alert" className="notice error">{validation}</p>}{action.feedback}<button className="primary" disabled={action.busy || !storeId || !categoryId || (!!parentId && !parent.data)}>{action.busy ? '사진을 전송하는 중…' : '사진 제출하기'}</button></form></div>; }
export function Owner({ path }: {
    path: string;
}) { const tail = path.slice('/store-owner'.length); const bits = tail.split('/').filter(Boolean); if (!bits.length || bits[0] === 'submissions' && !bits[1])
    return <SubmissionList />; if (bits[0] === 'submit')
    return <Submit />; if (bits[0] === 'submissions' && bits[1])
    return bits[2] === 'compare' ? <Comparison id={bits[1]}/> : <SubmissionDetail id={bits[1]}/>; if (bits[0] === 'issues')
    return <Issues id={bits[1]}/>; if (bits[0] === 'notifications')
    return <Notifications />; return <><h1>페이지를 찾을 수 없습니다</h1><Link to="/store-owner">이력 탐색으로</Link></>; }
