import {Link,useParams} from 'react-router-dom';
import {idempotencyKey} from '@storeloop/api-client';
import {useRef} from 'react';
import {useSession} from '../app/session';
import {api,useData,useList,useFilters,useAction,queryString,type Row,date} from '../shared/data';
import {ScopeFilters,SubmissionList} from '../shared/business';
import {Title,Panel,Metrics,Table,DataState,Badge,Rates,Pagination,Field,Form,Reason,Empty} from '../shared/ui';
import {drilldown,rateLabel} from '../shared/policy';
export function Dashboard(){const f=useFilters({is_active:'true'}),q=useData('/dashboard'+queryString(f.values));return <><Title title="매장 관제" description="제출 현황부터 사진 근거, 후속 조치까지 연결해 확인하세요."/><ScopeFilters filter={f}/><DataState query={q}>{d=><><Metrics items={[{name:'사진 제출',value:d.kpis.submission_count,to:'/ofc-admin/submissions'+queryString(drilldown(d.filters)),note:`전체 ${d.kpis.store_count}개 중 ${d.kpis.submitted_store_count}개 매장`},{name:'OFC 확인 필요',value:d.kpis.needs_ofc_review_count,to:'/ofc-admin/submissions'+queryString(drilldown(d.filters,{needs_ofc_review:true}))},{name:'미해결 요청',value:d.kpis.open_issue_count,to:'/ofc-admin/issues'+queryString(drilldown(d.filters,{unresolved:true}))},{name:'기술 실패',value:d.kpis.failed_count,to:'/ofc-admin/submissions'+queryString(drilldown(d.filters,{status:'failed'}))}]}/><Panel title="담당 범위의 현재 상태"><div className="summary-line"><span>평균 준수율 <b>{rateLabel(d.kpis.compliance_rate)}</b> · 판단 가능률 <b>{rateLabel(d.kpis.assessable_rate)}</b></span><span>평가 표본 {d.sample_count} · Mock 평가 {d.mock_review_count}</span><span>대기 {d.kpis.queued_count} · 분석 중 {d.kpis.running_count} · 완료 {d.kpis.succeeded_count}</span></div><Table caption="매장별 관제" rows={d.stores} columns={[{title:'매장',cell:r=><Link to={'/ofc-admin/stores/'+r.store_id}>{r.store_name}</Link>},{title:'상태',cell:r=><><Badge value={r.status}/>{r.latest_job&&<small>최근 분석 · <Badge value={r.latest_job.status}/></small>}</>},{title:'제출 / 평가',cell:r=>`${r.submission_count} / ${r.review_count}`},{title:'준수율 / 판단 가능률',cell:r=><Rates row={r}/>},{title:'확인 / 실패',cell:r=>`${r.needs_ofc_review_count} / ${r.failed_count}`},{title:'미해결',cell:r=><Link to={'/ofc-admin/issues'+queryString(drilldown(r.drilldown,{unresolved:true}))}>{r.open_issue_count}건</Link>},{title:'근거 확인',cell:r=><Link to={'/ofc-admin/submissions'+queryString(r.drilldown)}>기록 보기 →</Link>}]}/></Panel></>}</DataState></>;}
export function Stores(){const f=useFilters(),q=useList('/stores',f.values),{account}=useSession();return <><Title title="관리 매장" description="현재 담당 범위의 매장과 연결 상태를 확인합니다."/><Field label="매장 검색"><input value={f.values.q??''} onChange={e=>f.update('q',e.target.value)} placeholder="매장 이름 또는 코드"/></Field><Panel><DataState query={q}>{d=><><Table rows={d.items} caption="관리 매장 목록" columns={[{title:'매장',cell:r=><Link to={'/ofc-admin/stores/'+r.id}>{r.name}<small>{r.code}</small></Link>},{title:'지역 / 유형',cell:r=><>{r.region_name}<small>{r.store_type}</small></>},{title:'OFC',cell:r=>r.ofc?.display_name??'미배정'},{title:'상태',cell:r=>r.is_active?'활성':'비활성'}]}/><Pagination data={d} update={f.update}/></>}</DataState></Panel>{account.role==='ofc'&&<Candidates/>}</>;}
function Candidates(){const f=useFilters(),q=useList('/stores/candidates',{page:f.values.page??1}),key=useRef(idempotencyKey());const m=useAction((f:FormData)=>api.post('/stores/'+f.get('store_id')+'/claim',{reason:f.get('reason')},key.current));return <Panel title="미배정 매장 담당 등록"><p className="muted">같은 지역의 미배정 매장입니다. 담당 등록 이후 영업 기록을 볼 수 있습니다.</p><DataState query={q}>{d=><Form onSubmit={v=>m.mutate(v,{onSuccess:()=>{key.current=idempotencyKey();}})} pending={m.isPending} error={m.error} success={m.isSuccess} submit="담당 매장으로 등록"><Field label="등록할 매장"><select name="store_id" required><option value="">매장 선택</option>{d.items.map((s:Row)=><option key={s.id} value={s.id}>{s.name} · {s.region_name}</option>)}</select></Field><Reason/><Pagination data={d} update={f.update}/></Form>}</DataState></Panel>;}
export function StoreDetail(){const {id}=useParams(),q=useData('/stores/'+id);return <><Title title="매장 상세"/><DataState query={q}>{d=><Panel title={d.name}><dl><dt>매장 코드</dt><dd>{d.code}</dd><dt>지역</dt><dd>{d.region_name}</dd><dt>주소</dt><dd>{d.address||'등록된 주소 없음'}</dd><dt>담당 OFC</dt><dd>{d.ofc?.display_name??'미배정'}</dd><dt>운영 상태</dt><dd>{d.is_active?'활성':'비활성'}</dd></dl><div className="actions"><Link className="button" to={'/ofc-admin/submissions'+queryString({store_id:id})}>제출 사진 확인</Link><Link className="button secondary" to={'/ofc-admin/issues'+queryString({store_id:id})}>확인 요청</Link><Link className="button secondary" to={'/ofc-admin/guidelines'+queryString({store_id:id})}>매장 기준</Link></div></Panel>}</DataState></>;}
