import React, { useRef, useState } from 'react';
import { displayTime, payloadKey, roleLabel, statusLabel } from '../shared/policy';
import { api, Badge, Empty, Field, Link, Load, Notice, Pager, Table, backLink, choices, detailLink, go, pageQuery, queryString, useAction, useData, useLocation, type Page, type Row } from '../shared/ui';
function Overview() { const query = useData('/operations/status', true); return <div className="detail-workspace"><p className="eyebrow">PLATFORM EXPLORER</p><h1>상태와 연결 탐색</h1><p>현재 서비스 상태와 이용을 막는 연결 누락을 확인합니다.</p><Load query={query}>{(d: Row) => <><div className="operation-map"><section className="panel"><h2>계정 ↔ 매장 연결</h2><div className="connection-row"><Link to="/platform-admin/accounts?role=store_owner&mapping_status=missing"><strong>{d.data_quality.unmapped_owner_accounts}</strong>점주 연결 누락</Link><span aria-hidden="true">↔</span><Link to="/platform-admin/catalogs?kind=stores"><strong>{d.data_quality.unassigned_stores}</strong>OFC 미배정 매장</Link></div><Link to="/platform-admin/accounts?role=ofc&mapping_status=missing">OFC 연결 누락 {d.data_quality.unmapped_ofc_accounts}명 확인 →</Link></section><section className="panel"><h2>실제 처리 작업</h2><div className="job-counts">{Object.entries(d.jobs).map(([state, count]) => <Link to={'/platform-admin/jobs?status=' + state + '&is_fixture=false'} key={state}><Badge value={state}/><strong>{String(count)}</strong></Link>)}</div><h3>Mock 장애 사례</h3><p>{Object.entries(d.fixture_jobs).map(([s, c]) => statusLabel(s) + ' ' + c + '건').join(' · ')}</p><Link to="/platform-admin/jobs?is_fixture=true">Mock 작업 탐색 →</Link></section></div><section className="panel"><h2>서비스 구성요소</h2><Table caption="실제 가용 상태" head={['구성요소', '상태', '확인 시각', '최근 heartbeat', '오류 분류']}>{d.services.map((s: Row) => <tr key={s.name}><th>{s.name}</th><td><Badge value={s.status} label={s.status === 'unknown' ? '미확인' : undefined}/></td><td>{displayTime(s.checked_at)}</td><td>{displayTime(s.heartbeat_at)}</td><td>{s.error_code ?? '—'}</td></tr>)}</Table><p>Worker 마지막 heartbeat: {d.worker_heartbeat_age_seconds == null ? '확인되지 않음' : d.worker_heartbeat_age_seconds + '초 전'}</p></section><section className="panel"><h2>최근 실제 모델 사용 상태</h2><Badge value={d.model.readiness} label={d.model.readiness === 'unknown' ? '미확인' : undefined}/><p>성공 {displayTime(d.model.last_success_at)} · 실패 {displayTime(d.model.last_failure_at)}</p><p>{d.model.last_error_code ?? '최근 오류 없음'}</p><small>최근 실제 실행을 기준으로 표시합니다. 이 화면 갱신은 모델 분석을 실행하지 않습니다.</small></section></>}</Load></div>; }
function Accounts({ id }: {
    id?: string;
}) { const p = new URLSearchParams(useLocation().split('?')[1]); const query = useData<Page<Row>>('/operations/accounts' + queryString({ q: p.get('q'), role: p.get('role'), mapping_status: p.get('mapping_status'), is_active: p.get('is_active'), page: p.get('page') ?? 1, page_size: 12 })); const detail = useData<Row>(id && id !== 'new' ? '/operations/accounts/' + id : null); return <div className="detail-workspace"><div className="title-row"><div><p className="eyebrow">ACCOUNT ↔ ORGANIZATION</p><h1>계정과 연결 탐색</h1>{id && <Link to={backLink('/platform-admin/accounts')}>← 탐색 조건으로</Link>}</div><Link className="button primary" to="/platform-admin/accounts/new">일반 계정 생성</Link></div><div className="catalog-workspace"><aside className="catalog-list"><form onSubmit={e => { e.preventDefault(); go('/platform-admin/accounts' + queryString(Object.fromEntries(new FormData(e.currentTarget)))); }}><label>계정 이름·로그인 ID <input name="q" defaultValue={p.get('q') ?? ''}/></label><label>역할 <select name="role" defaultValue={p.get('role') ?? ''}><option value="">전체</option>{['store_owner', 'ofc', 'regional', 'hq', 'platform_operator'].map(r => <option value={r} key={r}>{roleLabel(r)}</option>)}</select></label><label>연결 상태 <select name="mapping_status" defaultValue={p.get('mapping_status') ?? ''}><option value="">전체</option>{['ready', 'missing', 'invalid'].map(v => <option value={v} key={v}>{statusLabel(v)}</option>)}</select></label><label>활성 상태 <select name="is_active" defaultValue={p.get('is_active') ?? ''}><option value="">전체</option><option value="true">활성</option><option value="false">비활성</option></select></label><button>계정 탐색</button></form><Load query={query}>{(d: Page<Row>) => <>{d.items.length ? d.items.map(a => <Link className={'explorer-item ' + (a.id === id ? 'selected' : '')} key={a.id} to={detailLink('/platform-admin/accounts/' + a.id)}><strong>{a.display_name}</strong><span>{a.login_id} / {roleLabel(a.role)}</span><small>{a.is_active ? '활성' : '비활성'} · {statusLabel(a.mapping_status)}</small></Link>) : <Empty />}<Pager data={d}/></>}</Load></aside><section>{id === 'new' ? <AccountForm key="new" refresh={query.refresh}/> : id ? <Load query={detail}>{(a: Row) => <AccountForm key={a.id} data={a} refresh={() => { query.refresh(); detail.refresh(); }}/>}</Load> : <Empty>계정을 선택해 역할·지역·매장 연결을 확인하세요.</Empty>}</section></div></div>; }
function AccountForm({ data, refresh }: {
    data?: Row;
    refresh: () => void;
}) { const regions = useData<Page<Row>>('/operations/regions?page_size=100'), stores = useData<Page<Row>>('/operations/stores?page_size=100'); const [draft, setDraft] = useState<Row>({ login_id: data?.login_id ?? '', display_name: data?.display_name ?? '', role: data?.role ?? 'store_owner', region_id: data?.region_id ?? '', is_active: data?.is_active ?? true, password: '', reason: '' }); const [mapping, setMapping] = useState<string[]>(data?.store_ids ?? []), [mappingReason, setMappingReason] = useState(''), [impact, setImpact] = useState<Row | null>(null); const action = useAction(refresh); const change = (k: string) => (v: string) => setDraft({ ...draft, [k]: v }); if (data?.role === 'platform_operator')
    return <section className="panel"><h2>{data.display_name}</h2><p>플랫폼 운영자 계정입니다. 운영자 생성·승격·변경은 이 화면에서 제공하지 않습니다.</p></section>; return <><form className="panel" onSubmit={async (e) => { e.preventDefault(); await action.run(async () => { let result: Row; if (data) {
    const body: Row = { version: data.version, display_name: draft.display_name, role: draft.role, region_id: ['hq', 'platform_operator'].includes(draft.role) ? null : draft.region_id || null, is_active: draft.is_active, reason: draft.reason };
    if (draft.password)
        body.password = draft.password;
    result = await api.patch<Row>('/operations/accounts/' + data.id, body);
    setImpact(result.impact);
    setMapping(result.account.store_ids);
}
else
    result = await api.post<Row>('/operations/accounts', { login_id: draft.login_id, display_name: draft.display_name, role: draft.role, region_id: draft.role === 'hq' ? null : draft.region_id || null, password: draft.password, reason: draft.reason }); setDraft({ ...draft, password: '' }); refresh(); if (!data)
    go('/platform-admin/accounts/' + result.id); }); }}><h2>{data ? '계정 권한 변경' : '일반 계정 생성'}</h2>{!data && <Field label="로그인 ID" name="login_id" value={draft.login_id} onChange={change('login_id')} required maxLength={80} minLength={3}/>}<Field label="표시 이름" name="display_name" value={draft.display_name} onChange={change('display_name')} required maxLength={120}/><Field label="역할" name="role" value={draft.role} onChange={v => setDraft({ ...draft, role: v, region_id: v === 'hq' ? '' : draft.region_id })} options={['store_owner', 'ofc', 'regional', 'hq'].map(value => ({ value, label: roleLabel(value) }))}/>{draft.role !== 'hq' && <Field label="소속 지역" name="region_id" value={draft.region_id} onChange={change('region_id')} options={choices(regions.data?.items.filter(r => r.is_active), '지역 없음')} required={['ofc', 'regional'].includes(draft.role)}/>}<Field label={data ? '새 비밀번호 (변경할 때만)' : '초기 비밀번호'} name="password" value={draft.password} onChange={change('password')} type="password" required={!data} minLength={12} maxLength={128}>12~128자. 저장한 비밀번호는 다시 표시하지 않습니다.</Field>{data && <label className="check"><input type="checkbox" checked={draft.is_active} onChange={e => setDraft({ ...draft, is_active: e.target.checked })}/>계정 활성</label>}<Field label="변경 사유" name="reason" value={draft.reason} onChange={change('reason')} required maxLength={500}/>{data && <Notice><strong>변경 영향 확인</strong><p>{data.display_name} · {roleLabel(data.role)} → {roleLabel(draft.role)} · {draft.is_active ? '활성 유지' : '이용 중지'}</p><p>비활성화·역할·범위 변경은 기존 로그인 상태에도 적용됩니다. 부적합한 매장 연결은 종료되며 과거 기록은 보존됩니다.</p></Notice>}{action.feedback}<button className="primary" disabled={action.busy}>{data ? '변경 저장' : '계정 생성'}</button></form>{impact && <Impact impact={impact}/>} {data && ['store_owner', 'ofc'].includes(data.role) && <form className="panel" onSubmit={async (e) => { e.preventDefault(); await action.run(async () => { const result = await api.put<Row>('/operations/accounts/' + data.id + '/mappings', { version: data.version, store_ids: mapping, reason: mappingReason }); setImpact(result.impact); refresh(); }, '매장 연결을 저장했습니다.'); }}><h2>매장 연결 정정</h2><p>현재 {data.store_ids.length}개 → 선택 {mapping.length}개. 선택한 매장으로 활성 연결 전체를 교체합니다.</p><Load query={stores}>{(d: Page<Row>) => d.items.filter(s => s.is_active && (data.role !== 'ofc' || s.region_id === data.region_id)).map(s => <label className="check" key={s.id}><input type="checkbox" checked={mapping.includes(s.id)} onChange={e => setMapping(e.target.checked ? [...mapping, s.id] : mapping.filter(v => v !== s.id))}/>{s.name} · {s.region_name}</label>)}</Load><Field label="연결 변경 사유" name="mapping_reason" value={mappingReason} onChange={setMappingReason} required maxLength={500}/><Notice>해제한 연결의 과거 행은 보존되며, 다음 요청부터 새 범위가 적용됩니다.</Notice><button disabled={action.busy}>매장 연결 저장</button></form>}</>; }
function Impact({ impact }: {
    impact: Row;
}) { return <Notice tone="success">종료된 연결 {impact.ended_mapping_ids.length}개 · 영향 매장 {impact.affected_store_ids.length}개 · 활성 세션 {impact.active_session_count}개 · {impact.new_business_blocked ? '신규 업무 제한' : '신규 업무 이용 가능'}</Notice>; }
function Catalogs() { const p = new URLSearchParams(useLocation().split('?')[1]); const kind = ['regions', 'stores', 'categories'].includes(p.get('kind') ?? '') ? p.get('kind')! : 'regions'; const name = { regions: '지역', stores: '매장', categories: '카테고리' }[kind]; const query = useData<Page<Row>>('/operations/' + kind + queryString({ page: p.get('page') ?? 1, page_size: 20, q: p.get('q') })); const selected = query.data?.items.find(v => v.id === p.get('edit')); return <div className="detail-workspace"><p className="eyebrow">ORGANIZATION EXPLORER</p><h1>기준 정보 · 지역·매장·카테고리</h1><nav className="subtabs" aria-label="기준 정보 종류">{Object.entries({ regions: '지역', stores: '매장', categories: '카테고리' }).map(([k, v]) => <Link className={kind === k ? 'active' : ''} to={'/platform-admin/catalogs?kind=' + k} key={k}>{v}</Link>)}</nav><div className="catalog-workspace"><aside className="catalog-list"><Link className="button primary" to={'/platform-admin/catalogs?kind=' + kind + '&edit=new'}>{name} 등록</Link><form onSubmit={e => { e.preventDefault(); go('/platform-admin/catalogs' + queryString({ kind, q: new FormData(e.currentTarget).get('q') })); }}><label>이름·코드 검색 <input name="q" defaultValue={p.get('q') ?? ''}/></label><button>검색</button></form><Load query={query}>{(d: Page<Row>) => <>{d.items.map(r => <Link className={'explorer-item ' + (selected?.id === r.id ? 'selected' : '')} to={'/platform-admin/catalogs' + queryString(Object.assign(Object.fromEntries(p), { edit: r.id }))} key={r.id}><strong>{r.name}</strong><span>{r.code} · {r.is_active ? '활성' : '비활성'}</span>{kind === 'stores' && <small>{r.region_name} · {r.ofc?.display_name ?? 'OFC 미배정'} · 점주 {r.owner_count}명</small>}</Link>)}{!d.items.length && <Empty />}<Pager data={d}/></>}</Load></aside><section>{p.get('edit') === 'new' ? <CatalogForm key={kind + 'new'} kind={kind} refresh={query.refresh}/> : selected ? <CatalogForm key={selected.id} kind={kind} data={selected} refresh={query.refresh}/> : <Empty>{name}을 선택해 상세와 활성 상태를 확인하세요.</Empty>}</section></div></div>; }
function CatalogForm({ kind, data, refresh }: {
    kind: string;
    data?: Row;
    refresh: () => void;
}) { const regions = useData<Page<Row>>(kind === 'stores' ? '/operations/regions?page_size=100' : null); const [draft, setDraft] = useState<Row>({ code: data?.code ?? '', name: data?.name ?? '', region_id: data?.region_id ?? '', store_type: data?.store_type ?? '', address: data?.address ?? '', description: data?.description ?? '', is_active: data?.is_active ?? true, reason: '' }); const [impact, setImpact] = useState<Row | null>(null); const action = useAction(refresh); const change = (k: string) => (v: string) => setDraft({ ...draft, [k]: v }); const name = { regions: '지역', stores: '매장', categories: '카테고리' }[kind]; return <><form className="panel" onSubmit={async (e) => { e.preventDefault(); await action.run(async () => { const body: Row = { name: draft.name, reason: draft.reason }; if (data)
    Object.assign(body, { version: data.version, is_active: draft.is_active });
else
    body.code = draft.code; if (kind === 'stores')
    Object.assign(body, { region_id: draft.region_id, store_type: draft.store_type, address: draft.address }); if (kind === 'categories')
    body.description = draft.description; const result = data ? await api.patch<Row>('/operations/' + kind + '/' + data.id, body) : await api.post<Row>('/operations/' + kind, body); setImpact(result.impact ?? null); refresh(); if (!data)
    go('/platform-admin/catalogs?kind=' + kind); }); }}><h2>{name} {data ? '변경' : '등록'}</h2>{!data && <Field label="코드" name="code" value={draft.code} onChange={change('code')} required maxLength={32}/>}<Field label="이름" name="name" value={draft.name} onChange={change('name')} required maxLength={120}/>{kind === 'stores' && <><Field label="지역" name="region_id" value={draft.region_id} onChange={change('region_id')} options={choices(regions.data?.items, '지역 선택')} required/><Field label="매장 형태" name="store_type" value={draft.store_type} onChange={change('store_type')} required maxLength={80}/><Field label="주소" name="address" value={draft.address} onChange={change('address')} maxLength={500}/></>}{kind === 'categories' && <Field label="설명" name="description" value={draft.description} onChange={change('description')} type="textarea" maxLength={2000}/>} {data && <label className="check"><input type="checkbox" checked={draft.is_active} onChange={e => setDraft({ ...draft, is_active: e.target.checked })}/>활성</label>}<Field label="변경 사유" name="reason" value={draft.reason} onChange={change('reason')} required maxLength={500}/>{data && <Notice>비활성화하면 신규 업무가 제한됩니다. 과거 제출·평가·연결 기록은 보존됩니다.{kind === 'stores' && ' 지역 변경으로 맞지 않는 OFC 연결은 종료됩니다.'}</Notice>}{action.feedback}<button className="primary" disabled={action.busy}>{data ? '변경 저장' : name + ' 등록'}</button></form>{impact && <Impact impact={impact}/>}</>; }
function Jobs({ id }: {
    id?: string;
}) { const p = new URLSearchParams(useLocation().split('?')[1]); const query = useData(id ? '/operations/jobs/' + id : '/operations/jobs' + queryString({ page: p.get('page') ?? 1, page_size: 12, status: p.get('status'), error_code: p.get('error_code'), is_fixture: p.get('is_fixture') }), !!id); if (id)
    return <div className="detail-workspace"><Link to={backLink('/platform-admin/jobs')}>← 처리 작업 탐색</Link><Load query={query}>{(d: Row) => <JobDetail key={id} data={d} refresh={query.refresh}/>}</Load></div>; return <div className="detail-workspace"><p className="eyebrow">JOB EXPLORER</p><h1>처리 작업과 실패 복구</h1><form className="search-grid" onSubmit={e => { e.preventDefault(); go('/platform-admin/jobs' + queryString(Object.fromEntries(new FormData(e.currentTarget)))); }}><label>작업 상태 <select name="status" defaultValue={p.get('status') ?? ''}><option value="">전체</option>{['queued', 'running', 'succeeded', 'failed'].map(v => <option key={v} value={v}>{statusLabel(v)}</option>)}</select></label><label>오류 분류 <input name="error_code" defaultValue={p.get('error_code') ?? ''}/></label><label>데이터 출처 <select name="is_fixture" defaultValue={p.get('is_fixture') ?? ''}><option value="">전체</option><option value="false">실제 처리 작업</option><option value="true">Mock 장애 사례</option></select></label><button>작업 탐색</button></form><Load query={query}>{(d: Page<Row>) => <>{d.items.length ? <Table caption="기술 처리 작업" head={['작업 번호', '상태', '접수 시각', '오류 분류', '시도 수']}>{d.items.map(j => <tr key={j.id}><th><Link to={detailLink('/platform-admin/jobs/' + j.id)}>{j.id.slice(0, 8)}</Link>{j.is_fixture && <small>Mock 장애 사례</small>}</th><td><Badge value={j.status}/></td><td>{displayTime(j.created_at)}</td><td>{j.error_code ?? '—'}</td><td>{j.attempt_count}</td></tr>)}</Table> : <Empty />}<Pager data={d}/></>}</Load></div>; }
function JobDetail({ data, refresh }: {
    data: Row;
    refresh: () => void;
}) { const [reason, setReason] = useState(''); const action = useAction(refresh); const key = useRef(payloadKey()).current; return <><h1>처리 작업 상세</h1><p className="mono">{data.id}</p><Badge value={data.status}/>{data.is_fixture && <span className="badge">Mock 장애 사례</span>}<p>{data.error_message ?? '현재 기록된 오류가 없습니다.'} {data.error_code && '(' + data.error_code + ')'}</p><p>접수 {displayTime(data.created_at)} · 종료 {displayTime(data.finished_at)}</p><section className="panel"><h2>보존된 처리 시도</h2>{data.attempts.length ? <ol className="attempt-chain">{data.attempts.map((a: Row) => <li key={a.id}><h3>시도 {a.attempt_number} <Badge value={a.status}/></h3><p>대기 {displayTime(a.queued_at)} → 시작 {displayTime(a.started_at)} → 종료 {displayTime(a.finished_at)}</p><p>결과 수용 기한 {displayTime(a.deadline_at)} · 점유 기한 {displayTime(a.lease_expires_at)}</p><p>{a.error_code ?? '오류 없음'} · {a.error_message ?? ''} · 결과 반영 {a.result_applied ? '예' : '아니오'}</p></li>)}</ol> : <Empty>아직 시작한 처리 시도가 없습니다.</Empty>}</section>{data.can_retry ? <form className="panel" onSubmit={async (e) => { e.preventDefault(); await action.run(async () => { const body = { reason }; await api.post('/operations/jobs/' + data.id + '/retry', body, key({ id: data.id, ...body })); refresh(); }, '실패 작업을 재처리 대기열에 넣었습니다.'); }}><h2>실패 작업 재처리</h2><Notice>종료된 실패 작업의 보존된 입력으로 새 시도를 만듭니다. 기존 실패 기록은 유지됩니다.</Notice><Field label="재처리 사유" name="reason" value={reason} onChange={setReason} required maxLength={500}/>{action.feedback}<button className="primary" disabled={action.busy}>실패 작업 재처리</button></form> : <Notice>대기·처리 중·성공한 작업은 재처리할 수 없습니다.</Notice>}</>; }
function Audit() { const p = new URLSearchParams(useLocation().split('?')[1]); const query = useData<Page<Row>>('/operations/audit' + queryString({ page: p.get('page') ?? 1, page_size: 20, actor_id: p.get('actor_id'), target_type: p.get('target_type'), target_id: p.get('target_id'), date_from: p.get('date_from'), date_to: p.get('date_to') })); return <div className="detail-workspace"><h1>운영 변경 이력</h1><p>수행자·대상·사유와 안전한 변경 요약을 조회합니다. 이력 수정·삭제는 제공하지 않습니다.</p><form className="search-grid" onSubmit={e => { e.preventDefault(); go('/platform-admin/audit' + queryString(Object.fromEntries(new FormData(e.currentTarget)))); }}>{[['actor_id', '수행자 ID'], ['target_type', '대상 종류'], ['target_id', '대상 ID'], ['date_from', '시작일'], ['date_to', '종료일']].map(([name, label]) => <label key={name}>{label}<input name={name} type={name.startsWith('date') ? 'date' : 'text'} defaultValue={p.get(name) ?? ''}/></label>)}<button>이력 탐색</button></form><Load query={query}>{(d: Page<Row>) => <>{d.items.length ? d.items.map(a => <details className="audit-item" key={a.id}><summary>{displayTime(a.created_at)} · {a.actor_name} · {a.action} · {a.outcome}</summary><p>{a.target_type} / {a.target_id}</p><p>변경 사유: {a.reason}</p><div className="compare-grid"><section><h3>변경 전</h3><pre>{JSON.stringify(a.before_data, null, 2)}</pre></section><section><h3>변경 후</h3><pre>{JSON.stringify(a.after_data, null, 2)}</pre></section></div></details>) : <Empty />}<Pager data={d}/></>}</Load></div>; }
function Announcements() { const query = useData<Page<Row>>('/operations/announcements' + pageQuery({}, false)); const [selected, setSelected] = useState<string | null>(null); const data = query.data?.items.find(a => a.id === selected); return <div className="detail-workspace"><div className="title-row"><h1>운영 공지</h1><button className="primary" onClick={() => setSelected('new')}>공지 작성</button></div><div className="catalog-workspace"><aside className="catalog-list"><Load query={query}>{(d: Page<Row>) => <>{d.items.map(a => <button className="explorer-item" key={a.id} onClick={() => setSelected(a.id)}><strong>{a.title}</strong><small>{a.is_active ? '활성' : '비활성'} · {displayTime(a.starts_at)}</small></button>)}{!d.items.length && <Empty />}<Pager data={d}/></>}</Load></aside><section>{selected && (selected === 'new' || data) ? <AnnouncementForm key={selected} data={data} refresh={query.refresh} onCreated={setSelected}/> : <Empty>공지를 선택하거나 새로 작성하세요.</Empty>}</section></div></div>; }
function AnnouncementForm({ data, refresh, onCreated }: {
    data?: Row;
    refresh: () => void;
    onCreated: (id: string) => void;
}) { const toLocal = (value: string) => { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }; const [draft, setDraft] = useState<Row>({ title: data?.title ?? '', body: data?.body ?? '', severity: data?.severity ?? 'info', starts_at: data?.starts_at ? toLocal(data.starts_at) : toLocal(new Date().toISOString()), ends_at: data?.ends_at ? toLocal(data.ends_at) : '', is_active: data?.is_active ?? true, reason: '' }); const action = useAction(refresh); const change = (k: string) => (v: string) => setDraft({ ...draft, [k]: v }); return <form className="panel" onSubmit={async (e) => { e.preventDefault(); await action.run(async () => { const body: Row = { title: draft.title, body: draft.body, severity: draft.severity, starts_at: new Date(draft.starts_at).toISOString(), ends_at: draft.ends_at ? new Date(draft.ends_at).toISOString() : null, reason: draft.reason }; if (data)
    Object.assign(body, { version: data.version, is_active: draft.is_active }); if (data)
    await api.patch('/operations/announcements/' + data.id, body);
else {
    const created = await api.post<Row>('/operations/announcements', body);
    onCreated(created.id);
} refresh(); window.dispatchEvent(new Event('announcement-updated')); }, '운영 공지를 저장했습니다.'); }}><h2>{data ? '공지 수정' : '새 공지'}</h2><Field label="공지 제목" name="title" value={draft.title} onChange={change('title')} required maxLength={160}/><Field label="안내 내용" name="body" type="textarea" value={draft.body} onChange={change('body')} required maxLength={4000}/><Field label="공지 종류" name="severity" value={draft.severity} onChange={change('severity')} options={[{ value: 'info', label: '안내' }, { value: 'maintenance', label: '점검' }]}/><div className="form-grid"><Field label="게시 시작 (현지 시각)" name="starts_at" type="datetime-local" value={draft.starts_at} onChange={change('starts_at')} required/><Field label="게시 종료 (현지 시각)" name="ends_at" type="datetime-local" value={draft.ends_at} onChange={change('ends_at')}/></div>{data && <label className="check"><input type="checkbox" checked={draft.is_active} onChange={e => setDraft({ ...draft, is_active: e.target.checked })}/>공지 활성</label>}<Field label="변경 사유" name="reason" value={draft.reason} onChange={change('reason')} required maxLength={500}/><section className="notice"><h3>게시 미리보기: {draft.title || '제목'}</h3><p>{draft.body || '안내 내용'}</p></section>{action.feedback}<button className="primary" disabled={action.busy}>공지 저장</button></form>; }
export function Platform({ path }: {
    path: string;
}) { const bits = path.slice('/platform-admin'.length).split('/').filter(Boolean); if (!bits.length)
    return <Overview />; if (bits[0] === 'accounts')
    return <Accounts id={bits[1]}/>; if (bits[0] === 'catalogs')
    return <Catalogs />; if (bits[0] === 'jobs')
    return <Jobs id={bits[1]}/>; if (bits[0] === 'audit')
    return <Audit />; if (bits[0] === 'announcements')
    return <Announcements />; return <><h1>페이지를 찾을 수 없습니다</h1><Link to="/platform-admin">상태와 연결 탐색으로</Link></>; }
