import {useState,useEffect,useCallback,useRef,createContext,useContext,type ReactNode,type FormEvent} from 'react';
import {api,ApiError,queryString,type AccountMe,type Page} from '@storeloop/api-client';
import {homeFor,rate,createMutationKeys} from './policy';
export {api,ApiError,queryString,rate};
export type Row=Record<string,any>;
export const Session=createContext<AccountMe|null>(null);
export const useAccount=()=>useContext(Session)!;
export const labels:Record<string,string>={store_owner:'점주',ofc:'OFC',regional:'지역 관리자',hq:'본사',platform_operator:'플랫폼 운영자',queued:'분석 대기',running:'분석 중',succeeded:'분석 완료',failed:'기술 실패',pass:'준수',fail:'개선 필요',unknown:'판단 불가',open:'접수',in_progress:'대응 중',resolved:'해결',not_submitted:'미제출',needs_attention:'확인 필요',processing:'처리 중',technical_failure:'기술 실패',unassessable:'판단 불가',evaluated:'평가 완료',high:'높음',normal:'보통',low:'낮음',available:'사용 가능',unavailable:'사용 불가',healthy:'정상',stale:'응답 지연',ready:'연결 완료',missing:'연결 필요',invalid:'연결 확인',similar:'유사',different:'차이 있음',insufficient_samples:'표본 부족',zero_variance:'값의 변화가 없어 계산 불가',resolved_change:'개선',unchanged:'변화 없음',regressed:'개선 필요',unavailable_change:'비교 불가'};
export const label=(value:unknown)=>value==null?'—':labels[String(value)]??String(value);
export const date=(value:unknown)=>value?new Date(String(value)).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
export function navigate(to:string,replace=false){history[replace?'replaceState':'pushState']({},'',to);window.dispatchEvent(new Event('popstate'));}
export function Link({to,children,className='',...props}:{to:string;children:ReactNode;className?:string;[key:string]:any}){return <a {...props} href={to} className={className} onClick={e=>{if(!e.ctrlKey&&!e.metaKey&&!e.shiftKey){e.preventDefault();navigate(to)}}}>{children}</a>}
export function useLocation(){const [loc,set]=useState(location.pathname+location.search);useEffect(()=>{const fn=()=>set(location.pathname+location.search);window.addEventListener('popstate',fn);return()=>window.removeEventListener('popstate',fn)},[]);return loc}
export function authError(error:unknown){if(error instanceof ApiError&&(error.status===401||(error.status===403&&error.code==='FORBIDDEN'))){window.dispatchEvent(new CustomEvent('session-check',{detail:error.status}));if(error.status===403)navigate('/forbidden',true);}}
export function useResource<T=Row>(path:string|null){const [data,setData]=useState<T|null>(null),[error,setError]=useState<unknown>(null),[busy,setBusy]=useState(false),[revision,bump]=useState(0);const serial=useRef(0);const refresh=useCallback(()=>bump(n=>n+1),[]);useEffect(()=>{setData(null);setError(null)},[path]);useEffect(()=>{const token=++serial.current;if(!path)return;setBusy(true);api.get<T>(path).then(v=>{if(serial.current===token){setData(v);setError(null)}}).catch(e=>{if(serial.current===token){setError(e);if(e instanceof ApiError&&[401,403,404].includes(e.status))setData(null);authError(e)}}).finally(()=>{if(serial.current===token)setBusy(false)});return()=>{serial.current++}},[path,revision]);return{data,error,busy,refresh}}
export function useAction(){const[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(null),[message,setMessage]=useState(''),pending=useRef(false);const run=async(fn:()=>Promise<unknown>,success?:()=>void)=>{if(pending.current)return;pending.current=true;setBusy(true);setError(null);setMessage('');try{await fn();setMessage('저장했습니다.');success?.()}catch(e){setError(e);authError(e)}finally{pending.current=false;setBusy(false)}};return{busy,error,message,run,clear:()=>{setError(null);setMessage('입력을 유지했습니다. 최신 정보를 확인한 뒤 저장해 주세요.')}}}
export function ErrorBox({error,retry}:{error:unknown;retry?:()=>void}){if(!error)return null;const e=error instanceof ApiError?error:null;return <div className="error-box" role="alert"><strong>{e?.code==='CSRF_INVALID'?'인증 확인값을 다시 갱신해야 합니다.':e?.status===409?'최신 정보가 변경되었습니다.':e?.status===403||e?.status===404?'이 정보에 접근할 수 없습니다.':'요청을 완료하지 못했습니다.'}</strong><p>{e?.message??'연결 상태를 확인해 주세요.'}</p>{e?.code==='CSRF_INVALID'&&<p>입력은 유지했습니다. 저장 버튼을 다시 누르면 인증 확인값을 갱신한 뒤 요청합니다.</p>}{e?.details?.map((d,i)=><p key={i}>{d.field}: {d.message}</p>)}{e?.requestId&&<small>요청 번호 {e.requestId}</small>}{retry&&<button type="button" onClick={retry}>최신 정보 다시 읽기</button>}</div>}
export function Resource({resource,children}:{resource:ReturnType<typeof useResource<any>>;children:(data:any)=>ReactNode}){return <><ErrorBox error={resource.error} retry={resource.refresh}/>{resource.busy&&<p className="loading" role="status">{resource.data?'최신 정보를 갱신하고 있습니다.':'정보를 불러오고 있습니다.'}</p>}{resource.data&&children(resource.data)}</>}
export function Empty({children='조건에 맞는 항목이 없습니다.'}:{children?:ReactNode}){return <div className="empty"><span aria-hidden="true">▧</span><p>{children}</p></div>}
export function Title({eyebrow,children,action}:{eyebrow:string;children:ReactNode;action?:ReactNode}){return <header className="page-title"><div><p className="eyebrow">{eyebrow}</p><h1 tabIndex={-1}>{children}</h1></div>{action}</header>}
export function Badge({value,children}:{value?:unknown;children?:ReactNode}){return <span className={'badge '+String(value??'')}>{children??label(value)}</span>}
export function Source({row}:{row:Row}){return <>{row.source_kind==='real_ai'&&<Badge value="pass">실제 AI 분석</Badge>}{row.source_kind==='mock'&&<Badge>Mock 데이터</Badge>}{(row.source_kind==='ai_generated_demo'||row.thumbnail?.source_kind==='ai_generated_demo')&&<Badge>AI 생성 시연 이미지</Badge>}</>}
export function Photo({photo,alt,className=''}:{photo?:Row;alt:string;className?:string}){const[failed,setFailed]=useState(false),[retry,setRetry]=useState(0);useEffect(()=>setFailed(false),[photo?.url]);if(!photo)return <div className="photo-placeholder">사진 없음</div>;return <div className={'photo '+className}>{failed?<div className="empty"><p>사진을 불러오지 못했습니다.</p><button onClick={()=>{setRetry(n=>n+1);setFailed(false)}}>사진 다시 보기</button></div>:<img key={retry} src={photo.url} alt={alt} onError={()=>setFailed(true)} loading="lazy"/>}</div>}
export function Field({label:caption,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="field"><span>{caption}</span>{children}{hint&&<small>{hint}</small>}</label>}
export function SelectItems({items,value,onChange,empty='전체',required=false}:{items:Row[];value:string;onChange:(v:string)=>void;empty?:string;required?:boolean}){return <select required={required} value={value} onChange={e=>onChange(e.target.value)}><option value="">{empty}</option>{items.map(v=><option key={v.id} value={v.id}>{v.name??v.display_name}</option>)}</select>}
export function FormStatus({action,onRefresh}:{action:ReturnType<typeof useAction>;onRefresh?:()=>void|Promise<void>}){const refresh=useAction();const conflict=action.error instanceof ApiError&&action.error.status===409;return <><ErrorBox error={action.error}/>{conflict&&onRefresh&&<button type="button" disabled={refresh.busy} onClick={()=>refresh.run(async()=>{await onRefresh();action.clear()})}>입력 유지하고 최신 정보 확인</button>}<ErrorBox error={refresh.error}/>{action.message&&<p role="status" className="success-note">{action.message}</p>}</>}
export function Pager({page}:{page:Page<any>}){const set=(n:number)=>{const q=new URLSearchParams(location.search);q.set('page',String(n));navigate(location.pathname+'?'+q)};return <div className="pager"><span>{page.total}개 · {page.page}페이지</span><button disabled={page.page<=1} onClick={()=>set(page.page-1)}>이전</button><button disabled={page.page*page.page_size>=page.total} onClick={()=>set(page.page+1)}>다음</button></div>}
export function listQuery(extra:Row={}){const p=new URLSearchParams(location.search),keep:Row={};for(const k of ['store_id','region_id','category_id','date_from','date_to','status','needs_ofc_review','is_active','page','q','unresolved','assignee_id','priority','error_code','is_fixture','role','mapping_status','target_type','target_id','actor_id','group_by','unread_only','level'])if(p.has(k))keep[k]=p.get(k);return queryString({...keep,...extra})}
export function Filters({kind='business',status=false,search=false,children}:{kind?:'business'|'simple';status?:boolean;search?:boolean;children?:ReactNode}){const account=useAccount();const stores=useResource<Page<Row>>(kind==='business'?'/stores?page_size=100':null),categories=useResource<Page<Row>>(kind==='business'?'/categories?page_size=100':null),regions=useResource<Page<Row>>(kind==='business'&&account.role!=='store_owner'?'/regions?page_size=100':null);const p=new URLSearchParams(location.search);const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget),q=new URLSearchParams();for(const[k,v]of form)if(v)q.set(k,String(v));navigate(location.pathname+(q.size?'?'+q:''))};return <form className="filters" onSubmit={submit} key={location.search}>{kind==='business'&&<>{regions.data&&<Field label="지역"><select name="region_id" defaultValue={p.get('region_id')??''}><option value="">모든 지역</option>{regions.data.items.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field>}<Field label="매장"><select name="store_id" defaultValue={p.get('store_id')??''}><option value="">모든 매장</option>{stores.data?.items.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="카테고리"><select name="category_id" defaultValue={p.get('category_id')??''}><option value="">모든 카테고리</option>{categories.data?.items.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field></>}{search&&<Field label="검색"><input name="q" defaultValue={p.get('q')??''} maxLength={120}/></Field>}<Field label="시작일 (UTC)"><input type="date" name="date_from" defaultValue={p.get('date_from')??''}/></Field><Field label="종료일 (UTC)"><input type="date" name="date_to" defaultValue={p.get('date_to')??''}/></Field>{status&&<Field label="분석 상태"><select name="status" defaultValue={p.get('status')??''}><option value="">전체</option>{['queued','running','succeeded','failed'].map(s=><option value={s} key={s}>{label(s)}</option>)}</select></Field>}{children}<button>조회</button><Link to={location.pathname} className="text-link">필터 초기화</Link></form>}
export function ContactSheet({items}:{items:Row[]}){const account=useAccount(),prefix=homeFor(account.role);return items.length?<div className="contact-sheet">{items.map((r,i)=><Link className="contact-card" key={r.id} to={`${prefix}/submissions/${r.id}${location.search}`}><div className="contact-image"><Photo photo={r.thumbnail} alt={`${r.store_name} ${r.category_name} 제출 사진`}/><span className="frame-number">{String(i+1).padStart(2,'0')}</span></div><div className="contact-caption"><div className="row spread"><small>{date(r.created_at)} · KST</small><Badge value={r.job?.status}/></div><h3>{r.store_name} <span>{r.category_name}</span></h3><div className="row"><Source row={r}/>{r.review_summary&&<Source row={r.review_summary}/>}</div><p>{r.review_summary?`준수 ${rate(r.review_summary.compliance_rate)} · 판단 가능 ${rate(r.review_summary.assessable_rate)}`:r.job?.status==='failed'?'기술 문제로 분석하지 못했어요. 운영자에게 재처리를 요청해 주세요.':'분석 결과를 기다리고 있어요.'}{r.parent_submission_id?' · 개선 후 제출':''}</p></div></Link>)}</div>:<Empty>선택한 기간에 제출한 사진이 없습니다.</Empty>}
export function Notifications(){const account=useAccount();const r=useResource<Page<Row>&{unread_count:number}>('/notifications'+listQuery()),action=useAction();return <><Title eyebrow="INBOX">알림</Title><FormStatus action={action}/><Resource resource={r}>{d=><><p>읽지 않은 알림 {d.unread_count}개</p>{d.items.length?d.items.map((n:Row)=><article className="paper row spread" key={n.id}><div><Badge>{n.read_at?'읽음':'새 알림'}</Badge><h3>{n.title}</h3><small>{date(n.created_at)}</small></div><button disabled={action.busy} onClick={()=>action.run(async()=>{await api.post(`/notifications/${n.id}/read`);navigate(`${homeFor(account.role)}/${n.target.type==='issue'?'issues':'submissions'}/${n.target.id}`)})}>내용 확인</button></article>):<Empty/>}<Pager page={d}/></>}</Resource></>}
export function Table({caption,columns,rows}:{caption:string;columns:{key:string;title:string;render?:(r:Row)=>ReactNode}[];rows:Row[]}){return <div className="table-scroll" role="region" aria-label={caption} tabIndex={0}><table><caption>{caption}</caption><thead><tr>{columns.map(c=><th key={c.key}>{c.title}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id??i}>{columns.map(c=><td key={c.key}>{c.render?c.render(r):r[c.key]??'—'}</td>)}</tr>)}</tbody></table>{!rows.length&&<Empty/>}</div>}

export function useMutationKeys(){return useRef(createMutationKeys()).current}
export function FileImage({file,alt}:{file:File;alt:string}){const[url,setUrl]=useState('');useEffect(()=>{const next=URL.createObjectURL(file);setUrl(next);return()=>URL.revokeObjectURL(next)},[file]);return <figure className="upload-preview">{url&&<img src={url} alt={alt}/>}<figcaption>{file.name} · {(file.size/1024/1024).toFixed(1)}MiB</figcaption></figure>}
