import test, { afterEach } from 'node:test';
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import React from 'react';
const dom = new JSDOM('<!doctype html><html><body></body></html>', { url: 'http://127.0.0.1:5177/store-owner/submit' });
Object.assign(globalThis, { window: dom.window, document: dom.window.document, HTMLElement: dom.window.HTMLElement, File: dom.window.File, Event: dom.window.Event, PopStateEvent: dom.window.PopStateEvent, history: dom.window.history });
Object.defineProperty(globalThis, 'navigator', { value: dom.window.navigator, configurable: true });
URL.createObjectURL = () => 'blob:local-test-image';
URL.revokeObjectURL = () => { };
const { render, fireEvent, waitFor, cleanup } = await import('@testing-library/react');
const { api, ApiError } = await import('@storeloop/api-client');
const { SessionContext } = await import('../src/shared/ui.tsx');
const { Owner } = await import('../src/store-owner/Owner.tsx');
const { Business } = await import('../src/ofc-admin/Business.tsx');
const original = { ...api };
const page = (items: any[]) => ({ items, total: items.length, page: 1, page_size: 100 });
const owner = { id: 'owner', login_id: 'test.owner', display_name: '테스트 점주', role: 'store_owner', region_id: 'region', is_active: true, version: 1, store_ids: ['store'], permissions: [] };
const manager = { ...owner, id: 'manager', role: 'hq' };
const options = (path: string) => path.startsWith('/stores') ? page([{ id: 'store', name: '테스트 매장', region_id: 'region', region_name: '테스트 지역', is_active: true, can_submit: true }]) : path.startsWith('/categories') ? page([{ id: 'category', name: '음료', is_active: true }]) : page([]);
function mount(component: any, account: any = owner) { return render(React.createElement(SessionContext.Provider, { value: { account, location: window.location.pathname, refreshIdentity: async () => { }, security: () => { } } }, component)); }
afterEach(() => { cleanup(); Object.assign(api, original); history.replaceState({}, '', '/store-owner/submit'); });
test('제출 CSRF 실패에도 사진·질문과 동일 재시도 키를 보존한다', async () => { (api as any).get = async (path: string) => options(path); const calls: any[] = []; (api as any).upload = async (...args: any[]) => { calls.push(args); if (calls.length === 1)
    throw new ApiError(403, 'CSRF_INVALID', '보안 확인 필요'); return { submission_id: 'new-submission' }; }; const view = mount(React.createElement(Owner, { path: '/store-owner/submit' })); await waitFor(() => assert.ok(view.getByRole('option', { name: '테스트 매장' }))); fireEvent.change(view.getByLabelText('매장 *'), { target: { value: 'store' } }); fireEvent.change(view.getByLabelText('카테고리 *'), { target: { value: 'category' } }); fireEvent.change(view.getByLabelText(/사진 선택/), { target: { files: [new File(['synthetic'], 'shelf.png', { type: 'image/png' })] } }); fireEvent.change(view.getByLabelText('질문 또는 현장 상황'), { target: { value: '앞줄 정렬을 확인해 주세요.' } }); fireEvent.click(view.getByRole('button', { name: '사진 제출하기' })); await waitFor(() => assert.ok(view.getByText('보안 확인 필요'))); assert.equal((view.getByLabelText('질문 또는 현장 상황') as HTMLTextAreaElement).value, '앞줄 정렬을 확인해 주세요.'); assert.ok(view.getByRole('img', { name: '선택 사진 1: shelf.png' })); fireEvent.click(view.getByRole('button', { name: '사진 제출하기' })); await waitFor(() => assert.equal(calls.length, 2)); assert.equal(calls[0][3], calls[1][3]); assert.equal(calls[1][2][0].file.name, 'shelf.png'); });
test('Reference 미리보기와 파일 삭제가 실제 입력 상태를 바꾼다', async () => { history.replaceState({}, '', '/ofc-admin/references/new'); (api as any).get = async (path: string) => options(path); const view = mount(React.createElement(Business, { path: '/ofc-admin/references/new' }), manager); fireEvent.change(view.getByLabelText(/사진 선택/), { target: { files: [new File(['synthetic'], 'reference.png', { type: 'image/png' })] } }); assert.ok(view.getByRole('img', { name: '선택 사진 1: reference.png' })); fireEvent.click(view.getByRole('button', { name: '사진 1 삭제' })); assert.equal(view.queryByRole('img', { name: '선택 사진 1: reference.png' }), null); });
test('OFC는 읽을 수 있는 본사 기준의 수정 버튼을 받지 않는다', async () => { history.replaceState({}, '', '/ofc-admin/guidelines/rule'); const rule = { id: 'rule', title: '본사 기준', rule_key: 'facing', level: 'HQ', region_id: null, store_id: null, category_id: null, is_active: true, version: 1, current_version: 1, current: { text: '앞줄 정렬', version: 1 } }; (api as any).get = async (path: string) => path === '/guidelines/rule' ? rule : path.startsWith('/guidelines') ? page(path.endsWith('versions?page_size=100') ? [] : [rule]) : options(path); const view = mount(React.createElement(Business, { path: '/ofc-admin/guidelines/rule' }), { ...manager, role: 'ofc' }); await waitFor(() => assert.ok(view.getByText('앞줄 정렬'))); assert.ok(!view.queryByRole('button', { name: '새 버전 저장' }), 'OFC에게 본사 기준 수정 버튼을 숨겨야 한다'); assert.ok(!view.queryByRole('button', { name: '기준 비활성화' })); });
test('기준 409 후 입력 초안을 유지하고 최신 version으로 명시 저장한다', async () => { history.replaceState({}, '', '/ofc-admin/guidelines/rule'); let version = 1; const rule = () => ({ id: 'rule', title: '기준', rule_key: 'facing', level: 'HQ', region_id: null, store_id: null, category_id: null, is_active: true, version, current_version: version, current: { text: '기존 내용', version } }); (api as any).get = async (path: string) => path === '/guidelines/rule' ? rule() : path.startsWith('/guidelines') ? page(path.includes('/versions') ? [] : [rule()]) : options(path); const calls: any[] = []; (api as any).post = async (path: string, body: any) => { calls.push(body); if (calls.length === 1) {
    version = 2;
    throw new ApiError(409, 'VERSION_CONFLICT', '기준이 변경되었습니다.');
} return rule(); }; const view = mount(React.createElement(Business, { path: '/ofc-admin/guidelines/rule' }), manager); await waitFor(() => assert.ok(view.getByLabelText('진열 기준 내용 *'))); fireEvent.change(view.getByLabelText('진열 기준 내용 *'), { target: { value: '내가 작성한 기준' } }); fireEvent.change(view.getByLabelText('변경 사유 *'), { target: { value: '회귀 확인' } }); fireEvent.click(view.getByRole('button', { name: '새 버전 저장' })); await waitFor(() => assert.ok(view.getByText('기준이 변경되었습니다.'))); await waitFor(() => assert.ok(view.getByText('현재 v2 · 활성'))); assert.equal((view.getByLabelText('진열 기준 내용 *') as HTMLTextAreaElement).value, '내가 작성한 기준'); fireEvent.click(view.getByRole('button', { name: '새 버전 저장' })); await waitFor(() => assert.equal(calls.length, 2)); assert.equal(calls[1].version, 2); assert.equal(calls[1].text, '내가 작성한 기준'); });
test('Reference 409은 최신 lineage 대상으로 재시도하고 설명·사진 초안을 보존한다', async () => { history.replaceState({}, '', '/ofc-admin/references/old'); let conflicted = false; const old = { id: 'old', lineage_id: 'lineage', version: 1, state_version: 1, caption: '기존 설명', store_id: null, category_id: 'category', is_active: true, photo: { id: 'photo', url: '/api/media/photo' } }; const latest = { ...old, id: 'latest', version: 2, state_version: 3 }; (api as any).get = async (path: string) => path === '/references/old' ? old : path.startsWith('/references') ? page(conflicted ? [latest, old] : [old]) : options(path); const calls: any[] = []; (api as any).upload = async (...args: any[]) => { calls.push(args); if (calls.length === 1) {
    conflicted = true;
    throw new ApiError(409, 'VERSION_CONFLICT', 'Reference가 변경되었습니다.');
} return { ...latest, id: 'new-revision' }; }; const view = mount(React.createElement(Business, { path: '/ofc-admin/references/old' }), manager); await waitFor(() => assert.ok(view.getByLabelText('Reference 설명 *'))); fireEvent.change(view.getByLabelText('Reference 설명 *'), { target: { value: '내 설명 초안' } }); fireEvent.change(view.getByLabelText('변경 사유 *'), { target: { value: '교체 확인' } }); fireEvent.change(view.getByLabelText(/사진 선택/), { target: { files: [new File(['synthetic'], 'new-reference.png', { type: 'image/png' })] } }); fireEvent.click(view.getByRole('button', { name: 'Reference 변경 저장' })); await waitFor(() => assert.ok(view.getByText(/최신 Reference v2/))); assert.equal((view.getByLabelText('Reference 설명 *') as HTMLTextAreaElement).value, '내 설명 초안'); assert.ok(view.getByRole('img', { name: '선택 사진 1: new-reference.png' })); fireEvent.click(view.getByRole('button', { name: 'Reference 변경 저장' })); await waitFor(() => assert.equal(calls.length, 2)); assert.equal(calls[1][0], '/references/latest'); assert.equal(calls[1][1].state_version, 3); assert.equal(calls[1][1].caption, '내 설명 초안'); });
test('현재 세션 401 이후 기존 업무 행을 비우고 로그인 화면을 표시한다', async () => { history.replaceState({}, '', '/store-owner'); (api as any).me = async () => owner; let revoked = false; (api as any).get = async (path: string) => { if (revoked)
    throw new ApiError(401, 'ACCOUNT_INACTIVE', '사용할 수 없는 계정입니다.'); if (path.startsWith('/submissions'))
    return page([{ id: 'private', store_name: '보호 매장', category_name: '음료', created_at: '2026-09-21T00:00:00Z', job: { status: 'succeeded' }, photo_count: 1, open_issue_count: 0 }]); return options(path); }; const { App } = await import('../src/app/App.tsx'); const view = render(React.createElement(App)); await waitFor(() => assert.ok(view.getByText(/보호 매장/))); revoked = true; (api as any).me = async () => { throw new ApiError(401, 'ACCOUNT_INACTIVE', '사용할 수 없는 계정입니다.'); }; fireEvent.click(view.getByRole('link', { name: '내 알림' })); await waitFor(() => assert.ok(view.getByRole('heading', { name: '업무 공간 로그인' }))); assert.ok(!view.queryByText(/보호 매장/)); });
test('점주 홈에서 연 탐색 조건을 상세 뒤로가기에서 보존한다', async () => { history.replaceState({}, '', '/store-owner/submissions/example?return=' + encodeURIComponent('/store-owner?store_id=store&category_id=category')); const { backLink } = await import('../src/shared/ui.tsx'); assert.equal(backLink('/store-owner/submissions'), '/store-owner?store_id=store&category_id=category'); history.replaceState({}, '', '/store-owner/submissions/example?return=' + encodeURIComponent('//external.invalid/x')); assert.equal(backLink('/store-owner/submissions'), '/store-owner/submissions'); });
test('운영자 영업 알림 직접 경로는 API 조회 없이 접근 불가로 끝난다', async () => { history.replaceState({}, '', '/platform-admin/notifications'); (api as any).me = async () => ({ ...manager, role: 'platform_operator' }); const calls: string[] = []; (api as any).get = async (path: string) => { calls.push(path); return page([]); }; const { App } = await import('../src/app/App.tsx'); const view = render(React.createElement(App)); await waitFor(() => assert.ok(view.getByRole('heading', { name: '접근할 수 없는 화면입니다' }))); assert.ok(!calls.some(path => path.startsWith('/notifications'))); });
const referenceSubmission = {id:'submission',store_id:'store',store_name:'테스트 매장',category_name:'음료',submitted_by_id:'owner',created_at:'2026-09-21T00:00:00Z',source_kind:'user_upload',question:'',photos:[],job:{status:'failed',error_code:'TEST_FAILURE',error_message:'합성 시험 상태'},review:null,parent:null,children:[],issues:[],context:{guidelines:[],references:[{reference_id:'ref-a',photo_id:'legacy-a',position:1,caption:'첫 기준 사진'},{reference_id:'ref-b',photo_id:'legacy-b',position:2,caption:'둘째 기준 사진'}]}};
test('MEDIA-CLARIFY-1은 snapshot 순서와 reference_id 대응으로 보호 URL·생성 배지를 표시한다',async()=>{history.replaceState({},'','/store-owner/submissions/submission');const calls:string[]=[];(api as any).get=async(path:string)=>{calls.push(path);return {...referenceSubmission,reference_photos:[{reference_id:'ref-b',photo:{id:'media-b',url:'/api/media/media-b',source_kind:'user_upload'}},{reference_id:'ref-a',photo:{id:'media-a',url:'/api/media/media-a',source_kind:'ai_generated_demo'}}]};};const view=mount(React.createElement(Owner,{path:'/store-owner/submissions/submission'}));await waitFor(()=>assert.ok(view.getByText('음료 점검 결과')));const imgs=view.getAllByRole('img',{hidden:true}) as HTMLImageElement[];assert.equal(imgs[0].getAttribute('src'),'/api/media/media-a');assert.equal(imgs[1].getAttribute('src'),'/api/media/media-b');assert.equal(view.getAllByText('AI 생성 시연 이미지').length,1);assert.ok(!calls.some(path=>path.startsWith('/references')));});
test('Reference 메타데이터가 없는 서버에는 기존 보호 URL을 쓰고 출처를 추정하지 않는다',async()=>{history.replaceState({},'','/store-owner/submissions/submission');(api as any).get=async()=>referenceSubmission;const view=mount(React.createElement(Owner,{path:'/store-owner/submissions/submission'}));await waitFor(()=>assert.ok(view.getByText('음료 점검 결과')));const imgs=view.getAllByRole('img',{hidden:true}) as HTMLImageElement[];assert.equal(imgs[0].getAttribute('src'),'/api/media/legacy-a');assert.ok(!view.queryByText('AI 생성 시연 이미지'));});
