import {useState} from 'react';
import {Link,useParams,useLocation} from 'react-router-dom';
import {api,ApiError,checked,queryString,useData,useSession,type Row,type Rows} from '../shared/data';
import {Heading,Card,DataState,Field,Photo,Tag,text,date,Empty,Filters,Pagination,useListPath,MutationForm,Reason,SelectRows,nullValue,values,UploadField,ErrorBox} from '../shared/ui';
function canWrite(account:Row,g:Row){return account.role==='hq'||(account.role==='regional'&&((g.level==='REGION'&&g.region_id===account.region_id)||!!g.store_id))||(account.role==='ofc'&&!!g.store_id);}
function GuidelineCreate({done}:{done:()=>void}){const {account}=useSession();const levels=account.role==='hq'?['HQ','REGION','STORE','CATEGORY']:account.role==='regional'?['REGION','STORE','CATEGORY']:['STORE','CATEGORY'];const [level,setLevel]=useState(levels[0]);const stores=useData<Rows>('/stores?is_active=true&page_size=100'),cats=useData<Rows>('/categories?is_active=true&page_size=100'),regions=useData<Rows>(account.role==='hq'?'/regions?page_size=100':null);return <MutationForm button="진열 기준 등록" onSave={f=>{const v=values(f);return api.post('/guidelines',{rule_key:v.rule_key,title:v.title,level,region_id:level==='REGION'?(account.role==='hq'?v.region_id:account.region_id):null,store_id:['STORE','CATEGORY'].includes(level)?nullValue(v.store_id):null,category_id:level==='CATEGORY'?v.category_id:null,text:v.text,reason:v.reason});}} onConflict={done} onDone={done}><Field label="적용 단계"><select value={level} onChange={e=>setLevel(e.target.value)}>{levels.map(v=><option key={v} value={v}>{text(v)}</option>)}</select></Field>{level==='REGION'&&account.role==='hq'&&<Field label="지역"><SelectRows name="region_id" rows={regions.data?.items??[]} required/></Field>}{['STORE','CATEGORY'].includes(level)&&<Field label="매장"><SelectRows name="store_id" rows={stores.data?.items??[]} required={level==='STORE'||account.role!=='hq'} blank={account.role==='hq'&&level==='CATEGORY'?'전체 공통':'선택해 주세요'}/></Field>}{level==='CATEGORY'&&<Field label="카테고리"><SelectRows name="category_id" rows={cats.data?.items??[]} required/></Field>}<Field label="기준 이름"><input name="title" required maxLength={160}/></Field><Field label="기준 식별 이름" hint="같은 기준은 같은 이름을 사용해 단계별 우선순위를 연결합니다. 영문 소문자·숫자·밑줄 (예: facing)"><input name="rule_key" required pattern="[a-z][a-z0-9_]{0,79}" maxLength={80}/></Field><Field label="진열 기준 내용"><textarea name="text" required maxLength={10000} rows={5}/></Field><Reason/></MutationForm>;}
export function Guidelines(){const {search}=useLocation();const s=useData<Rows>(useListPath('/guidelines',['store_id','region_id','category_id','level','is_active']));return <><Heading title="같은 기준으로, 함께 살펴봐요">본사부터 현장까지 이어지는 진열 기준을 관리합니다.</Heading><details className="card"><summary>＋ 새로운 진열 기준</summary><GuidelineCreate done={s.reload}/></details><Filters business dates={false} fields={[{name:'level',title:'적용 단계',options:['HQ','REGION','STORE','CATEGORY'].map(id=>({id,name:text(id)}))},{name:'is_active',title:'활성 상태',options:[{id:'true',name:'활성'},{id:'false',name:'비활성'}]}]}/><DataState state={s}><div className="grid">{s.data?.items.map(g=><Link className="standard-card card" to={'/ofc-admin/guidelines/'+g.id+search} key={g.id}><div className="section-title"><Tag value={g.level}/><small>v{g.current_version} · {g.is_active?'활성':'비활성'}</small></div><h2>{g.title}</h2><p>{g.current.text}</p><span className="quiet">기준과 변경 이력 →</span></Link>)}</div>{!s.data?.items.length&&<Empty/>}<Pagination data={s.data}/></DataState></>;}
export function GuidelineDetail(){const {search}=useLocation();const {id}=useParams();const s=useData('/guidelines/'+id),versions=useData<Rows>('/guidelines/'+id+'/versions?page_size=100');const {account}=useSession();const done=()=>{s.reload();versions.reload();};return <><Link className="back" to={"/ofc-admin/guidelines"+search}>← 진열 기준</Link><Heading title={s.data?.title??'진열 기준'}/><DataState state={s}>{s.data&&<><Card><Tag value={s.data.level}/><p className="preline">{s.data.current.text}</p><small>현재 v{s.data.current_version} · {s.data.is_active?'활성':'비활성'} · {date(s.data.updated_at)}</small></Card>{canWrite(account,s.data)&&<div className="grid"><details className="card"><summary>새 버전 작성</summary><MutationForm button="새 버전 저장" onSave={f=>api.post('/guidelines/'+id+'/versions',{version:s.data?.version,title:String(f.get('title')),text:String(f.get('text')),reason:String(f.get('reason'))})} onConflict={s.reload} onDone={done}><Field label="기준 이름"><input name="title" required defaultValue={s.data.title} maxLength={160}/></Field><Field label="진열 기준 내용"><textarea name="text" required defaultValue={s.data.current.text} maxLength={10000} rows={6}/></Field><Reason/></MutationForm></details><details className="card"><summary>{s.data.is_active?'기준 비활성화':'기준 활성화'}</summary><MutationForm confirm button={s.data.is_active?'비활성화':'활성화'} summary="앞으로 접수하는 분석에 적용할지 변경합니다. 과거 분석에 사용한 기준은 보존됩니다." onSave={f=>api.patch('/guidelines/'+id,{version:s.data?.version,is_active:!s.data?.is_active,reason:String(f.get('reason'))})} onConflict={s.reload} onDone={done}><Reason/></MutationForm></details></div>}</>}</DataState><section className="section"><h2>이어 온 기준의 이력</h2><DataState state={versions}><ol className="timeline">{versions.data?.items.map(v=><li key={v.version_id}><Card><h3>버전 {v.version}</h3><small>{date(v.created_at)}</small><p className="preline">{v.text}</p><p className="hint">변경 이유: {v.change_reason}</p></Card></li>)}</ol></DataState></section></>;}
export function References(){const s=useData<Rows>(useListPath('/references',['store_id','category_id','include_inactive']));const cats=useData<Rows>('/categories?is_active=true&page_size=100'),stores=useData<Rows>('/stores?is_active=true&page_size=100');const {account}=useSession();return <><Heading title="좋은 진열을 함께 나눠요">비교의 기준이 되는 사진과 설명을 관리합니다.</Heading><details className="card"><summary>＋ Reference 등록</summary><MutationForm button="Reference 등록" onSave={f=>api.upload('/references',{category_id:String(f.get('category_id')),store_id:nullValue(f.get('store_id')),caption:String(f.get('caption')),reason:String(f.get('reason'))},[{field:'photo',file:f.get('photo') as File}])} onConflict={s.reload} onDone={s.reload}><Field label="적용 매장"><SelectRows name="store_id" rows={stores.data?.items??[]} required={account.role!=='hq'} blank={account.role==='hq'?'전사 공통':'선택해 주세요'}/></Field><Field label="카테고리"><SelectRows name="category_id" rows={cats.data?.items??[]} required/></Field><Field label="사진 설명"><textarea name="caption" required maxLength={1000}/></Field><UploadField label="Reference 사진" required/><Reason/></MutationForm></details><Filters business dates={false} fields={[{name:'include_inactive',title:'과거 버전',options:[{id:'true',name:'비활성·과거 버전 포함'}]}]}/><DataState state={s}><div className="grid">{s.data?.items.map(ref=><Card key={ref.id}><Photo photo={ref.photo} title={ref.caption}/><div className="section-title"><strong>버전 {ref.version}</strong><span>{ref.is_active?'활성':'비활성'}</span></div><p>{ref.caption}</p><small>{date(ref.created_at)}</small>{(account.role==='hq'||!!ref.store_id)&&<><details><summary>사진·설명 새 버전</summary><ReferenceRevisionForm reference={ref} onDone={s.reload}/></details><details><summary>{ref.is_active?'비활성화':'활성화'}</summary><MutationForm confirm button={ref.is_active?'Reference 비활성화':'Reference 활성화'} summary="앞으로의 분석에 사용할지 변경합니다. 이전 분석의 참조 사진은 보존됩니다." onSave={f=>api.patch('/references/'+ref.id+'/status',{state_version:ref.state_version,is_active:!ref.is_active,reason:String(f.get('reason'))})} onConflict={s.reload} onDone={s.reload}><Reason/></MutationForm></details></>}</Card>)}</div>{!s.data?.items.length&&<Empty/>}<Pagination data={s.data}/></DataState></>;}

function ReferenceRevisionForm({reference,onDone}:{reference:Row;onDone:()=>void}){
 const [target,setTarget]=useState({id:reference.id,state_version:reference.state_version,version:reference.version});
 const [checking,setChecking]=useState(false),[lookupError,setLookupError]=useState<Error|null>(null),[refreshed,setRefreshed]=useState(false);
 const refreshTarget=async()=>{
  if(checking)return;
  setChecking(true);setLookupError(null);
  try{
   let latest:Row|null=null;
   for(let page=1;;page++){
    const result=await checked(api.get<Rows>('/references'+queryString({category_id:reference.category_id,store_id:reference.store_id,include_inactive:true,page,page_size:100})));
    for(const candidate of result.items){
     if(candidate.lineage_id===reference.lineage_id&&(!latest||candidate.version>latest.version||(candidate.version===latest.version&&candidate.state_version>latest.state_version)))latest=candidate;
    }
    if(page*result.page_size>=result.total)break;
   }
   if(!latest)throw new ApiError(404,'NOT_FOUND','현재 접근할 수 있는 최신 Reference를 찾지 못했습니다.');
   // 저장 대상만 바꾸고 사용자가 작성한 입력과 선택한 파일은 그대로 둔다.
   setTarget({id:latest.id,state_version:latest.state_version,version:latest.version});setRefreshed(true);
  }catch(error){setLookupError(error as Error);}finally{setChecking(false);}
 };
 return <>
  <MutationForm button="새 Reference 저장" onSave={f=>{
   const file=f.get('photo') as File;
   return api.upload('/references/'+target.id,{state_version:target.state_version,caption:String(f.get('caption')),reason:String(f.get('reason'))},file?.size?[{field:'photo',file}]:[],undefined,'PATCH');
  }} onConflict={()=>{void refreshTarget();}} onDone={onDone}>
   <Field label="사진 설명"><textarea name="caption" required defaultValue={reference.caption} maxLength={1000}/></Field>
   <UploadField label="교체할 사진 (선택)"/>
   <Reason/>
   {checking&&<p role="status">최신 Reference를 확인하고 있습니다.</p>}
   {refreshed&&<p className="hint" role="status">최신 버전 {target.version}의 정보를 확인했습니다. 입력한 사진·설명·사유는 유지했어요. 내용을 확인한 뒤 ‘새 Reference 저장’을 눌러 주세요.</p>}
   <ErrorBox error={lookupError} retry={()=>{void refreshTarget();}}/>
  </MutationForm>
 </>;
}
