import {useEffect,useRef,useState} from 'react';
import {useNavigate,useSearchParams} from 'react-router-dom';
import {idempotencyKey} from '@storeloop/api-client';
import {api,useData,useList,useAction,type Row} from '../shared/data';
import {Title,Panel,Form,Select,Field,ErrorBox,DataState} from '../shared/ui';
import {uploadError} from '../shared/policy';
export function Submit(){const [params]=useSearchParams(),parentId=params.get('parent_submission_id');const parent=useData(parentId?'/submissions/'+parentId:'');const stores=useList('/stores',{is_active:true,page_size:100}),categories=useList('/categories',{is_active:true,page_size:100});const [store,setStore]=useState(''),[category,setCategory]=useState(''),[files,setFiles]=useState<File[]>([]),[question,setQuestion]=useState(''),[validation,setValidation]=useState<string|null>(null),[previews,setPreviews]=useState<string[]>([]);const key=useRef({signature:'',key:idempotencyKey()});const navigate=useNavigate();
 useEffect(()=>{if(parent.data){setStore(parent.data.store_id);setCategory(parent.data.category_id);}},[parent.data]);useEffect(()=>{if(!store&&stores.data?.items.length===1)setStore(stores.data.items[0].id);},[stores.data,store]);
 useEffect(()=>{const urls=files.map(f=>URL.createObjectURL(f));setPreviews(urls);return()=>urls.forEach(url=>URL.revokeObjectURL(url));},[files]);
 const mutation=useAction(async()=>{const signature=JSON.stringify({store,category,question,parentId,files:files.map(f=>[f.name,f.size,f.lastModified])});if(signature!==key.current.signature)key.current={signature,key:idempotencyKey()};const startedAt=Date.now();const result=await api.upload<Row>('/submissions',{store_id:store,category_id:category,question,parent_submission_id:parentId},files.map(file=>({field:'photos',file})),key.current.key);sessionStorage.setItem('storeloop:last-upload-timing',JSON.stringify({submission_id:result.submission_id,started_at:startedAt,accepted_at:Date.now()}));navigate('/store-owner/submissions/'+result.submission_id);});
 const move=(i:number,step:number)=>{const next=[...files];[next[i],next[i+step]]=[next[i+step],next[i]];setFiles(next);};
 return <><Title title={parentId?'개선 사진 다시 제출':'사진으로 매대 점검'} description="매대 사진과 질문을 보내면 적용 기준에 따라 개선 방향을 확인할 수 있어요."/><div className="submit-grid"><Panel title="점검할 사진"><ErrorBox error={stores.error||categories.error||parent.error}/><Form disabled={!stores.data?.items.length||!categories.data?.items.length||!!parent.error} pending={mutation.isPending} error={mutation.error} onSubmit={()=>{const error=uploadError(files,question);setValidation(error);if(!error)mutation.mutate(undefined);}} submit="사진 접수하고 분석 시작"><div className="form-grid"><Select label="매장 (필수)" value={store} onChange={v=>!parentId&&setStore(v)} required empty="매장 선택" options={stores.data?.items??[]}/><Select label="카테고리 (필수)" value={category} onChange={v=>!parentId&&setCategory(v)} required empty="카테고리 선택" options={categories.data?.items??[]}/></div>{parentId&&<p className="notice">이전 제출과 같은 매장·카테고리로 연결됩니다.</p>}{stores.data?.items.length===0&&<p className="error">연결된 활성 매장이 없습니다. OFC에게 매장 연결을 요청해 주세요.</p>}<Field label="매대 사진 (필수, 1~5장)" hint="JPEG / PNG · 장당 최대 10MiB · 선택 순서대로 분석합니다."><input type="file" accept="image/jpeg,image/png" multiple onChange={e=>{setFiles([...files,...Array.from(e.target.files??[])]);e.target.value='';}}/></Field><div className="upload-previews">{files.map((file,i)=><article key={i}><img src={previews[i]} alt={`선택한 사진 ${i+1}`}/><strong>{i+1}. {file.name}</strong><small>{(file.size/1048576).toFixed(2)} MiB</small><div className="actions"><button type="button" className="secondary" disabled={i===0} onClick={()=>move(i,-1)} aria-label={`사진 ${i+1} 앞으로`}>←</button><button type="button" className="secondary" disabled={i===files.length-1} onClick={()=>move(i,1)} aria-label={`사진 ${i+1} 뒤로`}>→</button><button type="button" className="secondary" onClick={()=>setFiles(files.filter((_,n)=>n!==i))}>제거</button></div></article>)}</div><Field label="궁금한 점 (선택)" hint={`${question.length.toLocaleString()} / 2,000자`}><textarea value={question} maxLength={2000} onChange={e=>setQuestion(e.target.value)} rows={5} placeholder="예: 앞줄 진열과 가격표를 어떻게 정리하면 좋을까요?"/></Field>{validation&&<p role="alert" className="error">{validation}</p>}<p className="muted">제출 시점의 기준과 Reference가 적용됩니다. AI는 1차 검토를 돕고, 판단이 어려운 항목은 OFC가 확인합니다.</p></Form></Panel><aside><Panel title="잘 보이는 사진 촬영법"><ol><li>매대 전체와 상품 앞면이 보이게 촬영해 주세요.</li><li>흔들리지 않게 밝은 곳에서 촬영해 주세요.</li><li>가격표와 가려진 부분은 가까이 한 장 더 촬영해 주세요.</li></ol><p>접수 후 화면을 나가도 제출 이력에서 분석 상태를 확인할 수 있습니다.</p></Panel>{parent.data?.review&&<Panel title="지난 점검의 개선 항목">{parent.data.review.result.criteria.filter((r:Row)=>r.verdict!=='pass').map((r:Row)=><p key={r.rule_key}><strong>{r.rule_key}</strong><br/>{r.actions.join(' · ')||r.reason}</p>)}</Panel>}</aside></div></>;
}
