import React,{useState,useEffect} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {type AccountMe,type Page} from '@storeloop/api-client';
import {api,ApiError,Session,useAccount,useLocation,useResource,Resource,useAction,FormStatus,Title,Field,Link,navigate,label,Notifications,type Row} from '../shared/ui';
import {homeFor,canVisit,safeReturn} from '../shared/policy';
import {OwnerHome,History,Submit,SubmissionDetail,Comparison} from '../store-owner/pages';
import {Dashboard,Stores,Guidelines,References,Issues,Analytics} from '../ofc-admin/pages';
import {Operations,Accounts,Catalogs,Jobs,Audit,Announcements} from '../platform-admin/pages';
import './style.css';
function Login({onLogin}:{onLogin:(account:AccountMe)=>void}){const action=useAction();return <main className="login-layout"><section className="login-story"><Link className="wordmark" to="/login">StoreLoop <span>03 / 사진과 근거</span></Link><p className="eyebrow">EVERY DISPLAY TELLS A STORY</p><h1>사진 한 장.<br/>더 나은 다음 진열.</h1><p>현장의 기록과 판단의 근거를 함께 펼쳐 보세요.</p><div className="shelf-art" aria-hidden="true">{[1,2,3].map(row=><div className="shelf-row" key={row}>{[1,2,3,4,5,6,7,8].map(i=><span key={i} style={{height:36+(i*row%3)*16+'px',opacity:.4+(i%4)*.18}}/>)}</div>)}</div><p className="login-footer">EVIDENCE ATELIER · StoreLoop Concept 03</p></section><section className="login-form"><p className="eyebrow">WELCOME TO YOUR WORKSPACE</p><h2>작업실에 들어가기</h2><p>연결된 매장과 현재 역할에 맞는 업무를 보여드립니다.</p><form onSubmit={e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);action.run(async()=>{const result=await api.login(String(f.get('login_id')),String(f.get('password')));form.reset();onLogin(result.account)})}}><Field label="로그인 ID"><input name="login_id" autoComplete="username" required maxLength={80} autoFocus/></Field><Field label="비밀번호"><input name="password" type="password" autoComplete="current-password" required maxLength={128}/></Field><FormStatus action={action}/><button className="primary full" disabled={action.busy}>{action.busy?'접속 확인 중…':'로그인'}</button></form><small>시연 계정 정보는 로컬 실행 안내를 확인해 주세요.</small></section></main>}
const ownerMenu=[['','사진 작업실'],['/submit','사진 제출'],['/history','사진 이력'],['/issues','문의·조치'],['/notifications','알림']];
const businessMenu=[['','사진 관제'],['/stores','매장'],['/submissions','사진 이력'],['/guidelines','진열 기준'],['/references','Reference'],['/issues','문의·조치'],['/analytics','추이·분석'],['/notifications','알림']];
const operationMenu=[['','서비스 흐름'],['/accounts','계정·접근 범위'],['/catalogs','기준 정보'],['/jobs','처리 작업'],['/audit','변경 이력'],['/announcements','운영 공지']];
function Shell({children,onLogout}:{children:React.ReactNode;onLogout:()=>void}){const account=useAccount(),prefix=homeFor(account.role),menu=account.role==='store_owner'?ownerMenu:account.role==='platform_operator'?operationMenu:businessMenu,announcements=useResource<Page<Row>>('/announcements'),[dismissed,setDismissed]=useState<string[]>([]),action=useAction();return <><a className="skip-link" href="#main">본문으로 건너뛰기</a><header className="masthead"><Link to={prefix} className="wordmark">StoreLoop <span>03 / 사진과 근거</span></Link><div className="account"><span>{account.display_name}<small>{label(account.role)} · {account.role==='hq'?'전체 매장':account.role==='regional'?'소속 지역':account.role==='ofc'?'담당 매장':account.role==='store_owner'?'연결 매장':'운영 정보'}</small></span><button onClick={()=>action.run(async()=>{await api.logout();onLogout()})} disabled={action.busy}>로그아웃</button></div></header><nav className="tool-rail" aria-label="업무 탐색">{menu.map(([path,text])=><Link key={path} to={prefix+path} aria-current={(location.pathname===prefix+path||(path&&location.pathname.startsWith(prefix+path+'/')))?'page':undefined}>{text}</Link>)}</nav><main id="main" className="workspace"><FormStatus action={action}/>{announcements.data?.items.filter(a=>!dismissed.includes(a.id)).map(a=><aside className="announcement" key={a.id}><div><strong>{a.title}</strong><p>{a.body}</p></div><button onClick={()=>setDismissed(v=>[...v,a.id])} aria-label={`${a.title} 공지 닫기`}>닫기</button></aside>)}{children}</main><footer className="footer"><span>StoreLoop · Evidence Atelier</span><span>AI는 보조 판단입니다. 현장 예외는 OFC와 함께 확인하세요.</span></footer></>}
function Routes(){const account=useAccount(),prefix=homeFor(account.role),path=location.pathname.slice(prefix.length).split('/').filter(Boolean),[page,id,sub]=path;if(page==='notifications'&&account.role!=='platform_operator')return <Notifications/>;if(account.role==='store_owner'){if(!page)return <OwnerHome/>;if(page==='submit')return <Submit/>;if(page==='history')return <History/>;if(page==='submissions'&&id)return sub==='compare'?<Comparison id={id}/>:<SubmissionDetail id={id}/>;if(page==='issues')return <Issues id={id}/>}
if(['ofc','regional','hq'].includes(account.role)){if(!page)return <Dashboard/>;if(page==='stores')return <Stores id={id}/>;if(page==='guidelines')return <Guidelines id={id}/>;if(page==='references')return <References/>;if(page==='submissions')return id?(sub==='compare'?<Comparison id={id}/>:<SubmissionDetail id={id}/>):<History/>;if(page==='issues')return <Issues id={id}/>;if(page==='analytics')return <Analytics/>}
if(account.role==='platform_operator'){if(!page)return <Operations/>;if(page==='accounts')return <Accounts id={id}/>;if(page==='catalogs')return <Catalogs/>;if(page==='jobs')return <Jobs id={id}/>;if(page==='audit')return <Audit/>;if(page==='announcements')return <Announcements/>}
return <><Title eyebrow="NOT FOUND">화면을 찾을 수 없습니다.</Title><Link className="button" to={prefix}>작업실로 돌아가기</Link></>}
function App(){const loc=useLocation(),[account,setAccount]=useState<AccountMe|null>(null),[checking,setChecking]=useState(true),[sessionError,setSessionError]=useState('');useEffect(()=>{let active=true;const check=async()=>{try{const me=await api.me();if(active){setAccount(me);setSessionError('')}}catch(e){if(active){if(e instanceof ApiError&&e.status===401)setAccount(null);else setSessionError('접속 정보를 확인하지 못했습니다. 연결을 확인하고 새로고침해 주세요.')}}finally{if(active)setChecking(false)}};check();const timer=setInterval(check,15000),focus=()=>{if(document.visibilityState==='visible')check()},event=(e:Event)=>{if((e as CustomEvent).detail===401){setAccount(null);navigate('/login',true)}else check()};window.addEventListener('focus',focus);document.addEventListener('visibilitychange',focus);window.addEventListener('session-check',event);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',focus);document.removeEventListener('visibilitychange',focus);window.removeEventListener('session-check',event)}},[]);useEffect(()=>{if(checking)return;if(!account){if(location.pathname!=='/login')navigate('/login?return='+encodeURIComponent(loc),true);return}if(location.pathname==='/login'||location.pathname==='/')navigate(safeReturn(account.role,new URLSearchParams(location.search).get('return')),true);else if(!canVisit(account.role,location.pathname)&&!['/forbidden','/not-found'].includes(location.pathname))navigate('/forbidden',true)},[account,checking,loc]);useEffect(()=>{const timer=setTimeout(()=>document.querySelector<HTMLElement>('h1')?.focus({preventScroll:true}),30);return()=>clearTimeout(timer)},[loc.split('?')[0]]);if(checking)return <main className="session-loading" role="status">작업실을 준비하고 있습니다…</main>;if(!account)return <>{sessionError&&<p role="alert">{sessionError}</p>}<Login onLogin={me=>{setAccount(me);navigate(safeReturn(me.role,new URLSearchParams(location.search).get('return')),true)}}/></>;const signature=JSON.stringify([account.id,account.role,account.region_id,account.store_ids,account.version]);return <Session.Provider value={account}><Shell key={signature} onLogout={()=>{setAccount(null);navigate('/login',true)}}>{sessionError?<div className="error-box" role="alert">{sessionError}<button onClick={()=>location.reload()}>접속 재확인</button></div>:canVisit(account.role,location.pathname)?<Routes key={loc.split('?')[0]}/>:<><Title eyebrow="ACCESS">접근할 수 없는 화면입니다.</Title><Link to={homeFor(account.role)} className="button">내 작업실로 돌아가기</Link></>}</Shell></Session.Provider>}
// HMR이 진입점을 다시 평가해도 같은 DOM에는 기존 React root를 재사용한다.
const rootKey = Symbol.for("storeloop.concept-03.react-root");
const container = document.getElementById("root") as (HTMLElement & { [rootKey]?: Root }) | null;
if (container) {
  const root = container[rootKey] ?? (container[rootKey] = createRoot(container));
  root.render(<React.StrictMode><App/></React.StrictMode>);
}
