import {useEffect, useId, useRef, useState, type ReactNode, type FormEvent} from 'react';
import {Link} from 'react-router-dom';
import {type UseQueryResult} from '@tanstack/react-query';
import {ApiError, type Row, date} from './data';
import {rateLabel} from './policy';
export function Title({title,description,action}:{title:string;description?:string;action?:ReactNode}){return <header className="page-title"><div><p className="eyebrow">STORELOOP / 관제 데스크</p><h1>{title}</h1>{description&&<p className="muted">{description}</p>}</div>{action}</header>;}
export function Panel({title,children,className=''}:{title?:string;children:ReactNode;className?:string}){return <section className={'panel '+className}>{title&&<h2>{title}</h2>}{children}</section>;}
export function Empty({children='선택한 조건에 해당하는 기록이 없습니다.'}:{children?:ReactNode}){return <div className="empty"><span aria-hidden="true">▤</span><p>{children}</p></div>;}
export function Loading(){return <div className="loading" role="status">정보를 불러오고 있습니다…<div className="skeleton"/><div className="skeleton"/></div>;}
export function ErrorBox({error,retry}:{error:unknown;retry?:()=>void}){if(!error)return null;const e=error as ApiError;return <div className="error" role="alert"><strong>{e.code==='CSRF_INVALID'?'보안 확인이 만료되었습니다. 입력은 유지했으니 다시 시도해 주세요.':e.status===403?'현재 권한으로 접근할 수 없습니다.':e.status===404?'기록을 찾을 수 없습니다.':e.status===409?'다른 변경이 먼저 적용되었습니다. 최신 정보를 확인해 주세요.':e.message||'요청을 처리하지 못했습니다.'}</strong>{e.details?.map((d,i)=><p key={i}>{d.field}: {d.message}</p>)}{e.requestId&&<small>요청 번호 {e.requestId}</small>}{retry&&<button type="button" className="secondary" onClick={retry}>다시 조회</button>}</div>;}
export function DataState({query,children}:{query:UseQueryResult<any>;children:(data:any)=>ReactNode}){if(query.isPending)return <Loading/>;if(query.isError)return <ErrorBox error={query.error} retry={()=>query.refetch()}/>;return <><div aria-live="polite" className="refresh">{query.isFetching?'최신 정보를 확인하고 있습니다…':''}</div>{children(query.data)}</>;}
const labels:Record<string,string>={queued:'분석 대기',running:'분석 중',succeeded:'분석 완료',failed:'기술 실패',pass:'준수',fail:'개선 필요',unknown:'판단 불가',open:'열림',in_progress:'조치 중',resolved:'해결',high:'높음',medium:'보통',low:'낮음',normal:'보통',urgent:'긴급',ready:'연결 완료',missing:'연결 누락',invalid:'연결 확인 필요',not_submitted:'미제출',needs_attention:'확인 필요',processing:'처리 중',technical_failure:'기술 실패',unassessable:'판단 불가',evaluated:'평가 완료',healthy:'정상',degraded:'주의',unavailable:'사용 불가',expired:'기한 만료',similar:'유사',different:'차이 있음',resolved_change:'개선',unchanged:'변화 없음',regressed:'악화',store_owner:'점주',ofc:'OFC',regional:'지역 관리자',hq:'본사',platform_operator:'플랫폼 운영자'};
export function label(value:string){return labels[value]??value;}
export function Badge({value}:{value?:string|null}){return <span className={'badge '+(value??'unknown')}>{label(value??'unknown')}</span>;}
export function Source({value}:{value?:string}){return value==='mock'?<span className="badge fail">Mock 데이터</span>:value==='ai_generated_demo'?<span className="badge unknown">AI 생성 시연 이미지</span>:value==='real_ai'?<span className="badge pass">실제 AI 분석</span>:null;}
export function Metrics({items}:{items:{name:string;value:ReactNode;to?:string;note?:string}[]}){return <div className="metrics">{items.map(i=><div className="metric" key={i.name}><span>{i.name}</span><strong>{i.to?<Link to={i.to}>{i.value}</Link>:i.value}</strong>{i.note&&<small>{i.note}</small>}</div>)}</div>;}
export function Rates({row}:{row:Row}){return <span className="rates"><b>{rateLabel(row.compliance_rate)}</b><small>판단 가능 {rateLabel(row.assessable_rate)}</small></span>;}
export type Column={title:string;cell:(row:Row)=>ReactNode};
export function Table({rows,columns,caption,mobileCards=false}:{rows:Row[];columns:Column[];caption:string;mobileCards?:boolean}){return !rows.length?<Empty/>:<><p className="scroll-hint">좁은 화면에서는 표를 좌우로 이동할 수 있습니다.</p><div className={'table-scroll '+(mobileCards?'mobile-cards':'')} role="region" aria-label={caption} tabIndex={0}><table><caption>{caption}</caption><thead><tr>{columns.map(c=><th key={c.title} scope="col">{c.title}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id??i}>{columns.map(c=><td key={c.title} data-label={c.title}>{c.cell(r)}</td>)}</tr>)}</tbody></table></div></>;}
export function Pagination({data,update}:{data:Row;update:(k:string,v:string)=>void}){return <div className="pagination"><span>전체 {data.total}건 · {data.page} / {Math.max(1,Math.ceil(data.total/data.page_size))}페이지</span><label>페이지 크기<select value={data.page_size} onChange={e=>update('page_size',e.target.value)}><option value="20">20개</option><option value="50">50개</option></select></label><button className="secondary" disabled={data.page<=1} onClick={()=>update('page',String(data.page-1))}>이전</button><button className="secondary" disabled={data.page*data.page_size>=data.total} onClick={()=>update('page',String(data.page+1))}>다음</button></div>;}
export function Field({label:labelText,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="field"><span>{labelText}</span>{children}{hint&&<small>{hint}</small>}</label>;}
export function TextInput({name,label:labelText,defaultValue='',required=false,maxLength=200,type='text'}:{name:string;label:string;defaultValue?:string|number;required?:boolean;maxLength?:number;type?:string}){return <Field label={labelText}><input name={name} type={type} defaultValue={defaultValue} required={required} maxLength={maxLength}/></Field>;}
export function Select({name,label:labelText,options,value,onChange,defaultValue='',required=false,empty='전체'}:{name?:string;label:string;options:Row[];value?:string;onChange?:(v:string)=>void;defaultValue?:string;required?:boolean;empty?:string}){return <Field label={labelText}><select name={name} {...(value!==undefined?{value,onChange:e=>onChange?.(e.target.value)}:{defaultValue})} required={required}><option value="">{empty}</option>{options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></Field>;}
export function Form({onSubmit,pending,disabled,error,success,children,submit='저장'}:{onSubmit:(data:FormData)=>void;pending?:boolean;disabled?:boolean;error?:unknown;success?:boolean;children:ReactNode;submit?:string}){return <form className="form" onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();onSubmit(new FormData(e.currentTarget));}}><ErrorBox error={error}/>{success&&<p role="status" className="notice">변경 사항을 저장했습니다. 현재 정보에 반영되었습니다.</p>}{children}<button disabled={pending||disabled} type="submit">{pending?'처리 중…':submit}</button></form>;}
export function Reason(){return <TextInput name="reason" label="변경 사유 (필수)" required maxLength={500}/>;}
export function Disclosure({title,children}:{title:string;children:ReactNode}){return <details className="disclosure"><summary>{title}</summary><div>{children}</div></details>;}
export function Photos({photos}:{photos:Row[]}){const [index,setIndex]=useState(0);const photo=photos[index]??photos[0];const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[photo?.id]);if(!photo)return <Empty>첨부된 사진이 없습니다.</Empty>;return <div className="photos">{failed?<p className="error">사진을 표시할 수 없습니다. 권한 또는 연결을 확인하고 다시 조회해 주세요.</p>:<a href={photo.url} target="_blank" rel="noreferrer" aria-label={`사진 ${index+1} 원본 새 창 보기`}><img className="main-photo" src={photo.url} alt={`진열 상태 사진 ${index+1}`} onError={()=>setFailed(true)}/></a>}<p>사진 {index+1}/{photos.length} · 원본을 누르면 확대됩니다.</p><Source value={photo.source_kind}/><div className="thumbnails">{photos.map((p,i)=><button type="button" className={index===i?'selected':'secondary'} aria-label={`사진 ${i+1} 선택`} aria-pressed={index===i} key={p.id??i} onClick={()=>setIndex(i)}><img src={p.thumbnail_url||p.url} alt=""/>{i+1}</button>)}</div></div>;}
export function Tabs({items}:{items:{title:string;content:ReactNode}[]}){const [active,setActive]=useState(0);const id=useId();const refs=useRef<(HTMLButtonElement|null)[]>([]);return <div><div className="tabs" role="tablist">{items.map((item,i)=><button ref={el=>{refs.current[i]=el;}} id={`${id}-tab-${i}`} key={i} role="tab" aria-selected={i===active} aria-controls={`${id}-panel-${i}`} tabIndex={i===active?0:-1} onClick={()=>setActive(i)} onKeyDown={e=>{const n=e.key==='ArrowRight'?(i+1)%items.length:e.key==='ArrowLeft'?(i+items.length-1)%items.length:e.key==='Home'?0:e.key==='End'?items.length-1:null;if(n!==null){e.preventDefault();setActive(n);refs.current[n]?.focus();}}}>{item.title}</button>)}</div>{items.map((item,i)=><div key={i} id={`${id}-panel-${i}`} role="tabpanel" aria-labelledby={`${id}-tab-${i}`} hidden={i!==active}>{item.content}</div>)}</div>;}
export function DateCell({value}:{value:string}){return <time dateTime={value}>{date(value)}</time>;}
