import test,{afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {StrictMode,createElement as h} from 'react';
const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'http://localhost:5175/store-owner/submit'});
for(const name of ['window','document','HTMLElement','HTMLInputElement','HTMLFormElement','Event','CustomEvent','MouseEvent','FormData','File','history','location','sessionStorage'])Object.defineProperty(globalThis,name,{value:(dom.window as any)[name],configurable:true,writable:true});
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});
const {render,screen,fireEvent,waitFor,cleanup}=await import('@testing-library/react');
const {api,Session}=await import('../src/shared/ui.tsx');
const {Submit}=await import('../src/store-owner/pages.tsx');
const original={get:api.get,upload:api.upload,create:URL.createObjectURL,revoke:URL.revokeObjectURL};
const account={id:'file-owner',login_id:'synthetic-owner',display_name:'검증 점주',role:'store_owner',region_id:null,is_active:true,version:1,store_ids:['s1'],permissions:['submit']};
afterEach(()=>{cleanup();api.get=original.get;api.upload=original.upload;URL.createObjectURL=original.create;URL.revokeObjectURL=original.revoke;history.replaceState({},'','/store-owner/submit');sessionStorage.clear();});

test('StrictMode의 지연 updater도 input 초기화 전에 선택한 파일을 보존하고 연속 선택 순서대로 제출한다',async()=>{
  let seq=0;const uploads:any[]=[];
  URL.createObjectURL=()=>`blob:selected-${++seq}`;URL.revokeObjectURL=()=>{};
  api.get=async(path:string)=>({items:[path.startsWith('/stores')?{id:'s1',name:'검증 매장',can_submit:true}:{id:'c1',name:'검증 음료'}],total:1,page:1,page_size:100}) as any;
  api.upload=async(path:string,body:any,files:any[])=>{uploads.push({path,body,files});return{submission_id:'submitted'} as any;};
  render(h(StrictMode,null,h(Session.Provider,{value:account as any},h(Submit))));
  await screen.findByRole('option',{name:'검증 매장'});
  fireEvent.change(screen.getByLabelText('매장'),{target:{value:'s1'}});
  fireEvent.change(screen.getByLabelText('카테고리'),{target:{value:'c1'}});
  const input=screen.getByLabelText(/^제출 사진/) as HTMLInputElement;
  let selected:File[]=[];
  // 실제 브라우저에서는 value=''가 FileList도 비운다. 단순 files 배열 주입은 이 동작을 생략한다.
  Object.defineProperty(input,'files',{configurable:true,get:()=>selected});
  Object.defineProperty(input,'value',{configurable:true,get:()=>selected.length?'C:\\fakepath\\shelf.png':'',set:(value:string)=>{assert.equal(value,'');selected=[];}});
  const first=new File(['first'],'shelf-first.png',{type:'image/png'}),second=new File(['second'],'shelf-second.png',{type:'image/png'});
  selected=[first];fireEvent.change(input);
  assert.equal(input.files?.length,0,'같은 파일을 다시 선택할 수 있도록 native input은 비워야 합니다.');
  await screen.findByAltText('제출할 사진 1');
  selected=[second];fireEvent.change(input);
  await screen.findByAltText('제출할 사진 2');
  assert.ok(screen.getByText(/shelf-first.png/));assert.ok(screen.getByText(/shelf-second.png/));
  fireEvent.click(screen.getByRole('button',{name:'사진 제출하기'}));
  await waitFor(()=>assert.equal(uploads.length,1));
  assert.equal(uploads[0].path,'/submissions');
  assert.deepEqual(uploads[0].files.map((part:any)=>part.file),[first,second]);
  assert.equal(location.pathname,'/store-owner/submissions/submitted');
});
