import test from 'node:test';
import assert from 'node:assert/strict';
import {homeFor,canVisit,rate,validatePhotos,safeReturn,shouldPoll,levelOptions} from '../src/shared/policy.ts';
test('다섯 역할의 직접 경로를 검증하고 운영자로 영업에 들어가지 못한다',()=>{assert.equal(homeFor('hq'),'/ofc-admin');assert.equal(canVisit('platform_operator','/ofc-admin/submissions/a'),false);assert.equal(canVisit('ofc','/ofc-admin/issues/a'),true);assert.equal(canVisit('store_owner','/store-ownerx'),false)});
test('로그인 return URL은 같은 역할 경로만 허용한다',()=>{assert.equal(safeReturn('store_owner','//evil.test'),'/store-owner');assert.equal(safeReturn('store_owner','/store-owner/history?store_id=a'),'/store-owner/history?store_id=a')});
test('결측 준수율을0점으로 만들지 않는다',()=>{assert.equal(rate(null),'—');assert.equal(rate(0),'0%')});
test('사진 장수·종류·장당 크기를 제출 전에 검증한다',()=>{assert.match(validatePhotos([]),/사진/);assert.match(validatePhotos([{type:'image/png',size:11*1024*1024}]),/10/);assert.match(validatePhotos([{type:'image/gif',size:1}]),/JPEG/);assert.equal(validatePhotos([{type:'image/png',size:1}]),'')});
test('종료 분석의 polling은 중단한다',()=>{assert.equal(shouldPoll('succeeded'),false);assert.equal(shouldPoll('failed'),false);assert.equal(shouldPoll('running'),true)});
test('기준 레벨은 현재 역할의 쓰기 범위에 한한다',()=>{assert.deepEqual(levelOptions('ofc'),['STORE','CATEGORY']);assert.deepEqual(levelOptions('regional'),['REGION','STORE','CATEGORY']);assert.deepEqual(levelOptions('hq'),['HQ','REGION','STORE','CATEGORY'])});

test('미해결 이슈 변경에 빈 해결 내용을 유효한 null로 보낸다', async()=>{const {issueChange}=await import('../src/shared/policy.ts');assert.equal(issueChange(3,{status:'in_progress',resolution:''}).resolution,null);assert.equal(issueChange(3,{status:'resolved',resolution:' 현장 확인 완료 '}).resolution,'현장 확인 완료')});

test('담당 등록·재처리 키는 대상 또는 본문 변경에 갱신하고 같은 요청에 유지한다',async()=>{const {createMutationKeys}=await import('../src/shared/policy.ts');let serial=0;const keys=createMutationKeys(()=>`synthetic-key-${++serial}`);const first=keys.get('/stores/one/claim',{reason:'담당 등록'});assert.equal(keys.get('/stores/one/claim',{reason:'담당 등록'}),first);const differentStore=keys.get('/stores/two/claim',{reason:'담당 등록'});assert.notEqual(differentStore,first);const job=keys.get('/operations/jobs/one/retry',{reason:'처리 복구'});assert.equal(keys.get('/operations/jobs/one/retry',{reason:'처리 복구'}),job);assert.notEqual(keys.get('/operations/jobs/one/retry',{reason:'수정한 사유'}),job);const beforeReset=keys.get('/operations/jobs/one/retry',{reason:'수정한 사유'});keys.reset();assert.notEqual(keys.get('/operations/jobs/one/retry',{reason:'수정한 사유'}),beforeReset)});
test('NOTIFY-CLARIFY-1 운영자의 영업 알림 직접 경로를 차단한다',()=>{assert.equal(canVisit('platform_operator','/platform-admin/notifications'),false);assert.equal(canVisit('platform_operator','/platform-admin/notifications?unread_only=true'),false);assert.equal(canVisit('platform_operator','/platform-admin/announcements'),true);assert.equal(canVisit('store_owner','/store-owner/notifications'),true);assert.equal(canVisit('hq','/ofc-admin/notifications'),true)});
