import test,{afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {createElement as h} from 'react';
const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'http://localhost:5175/store-owner/submissions/s1'});
for(const name of ['window','document','HTMLElement','Event','CustomEvent','FormData','File','history','location','sessionStorage'])Object.defineProperty(globalThis,name,{value:(dom.window as any)[name],configurable:true,writable:true});
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});
const {render,screen,cleanup}=await import('@testing-library/react');
const {api,Session}=await import('../src/shared/ui.tsx');
const {SubmissionDetail}=await import('../src/store-owner/pages.tsx');
const original=api.get;
const account={id:'owner1',login_id:'owner',display_name:'시연 점주',role:'store_owner',region_id:null,is_active:true,version:1,store_ids:['store1'],permissions:['submit']};
const detail={id:'s1',store_id:'store1',store_name:'시연 매장',category_name:'음료',created_at:'2026-09-21T00:00:00Z',submitted_by_id:'owner1',question:'',job:{status:'failed',error_message:'시연 실패',attempt_count:1},photos:[{id:'submission',url:'/api/media/submission',position:1}],review:null,context:{guidelines:[],references:[{reference_id:'a',photo_id:'old-a',caption:'첫 예시',position:1},{reference_id:'b',photo_id:'old-b',caption:'둘째 예시',position:2}]},parent:null,children:[],issues:[]};
afterEach(()=>{cleanup();api.get=original;});
test('MEDIA-CLARIFY-1: 순서가 다른 metadata를 ID로 연결해 보호URL과 실제 생성출처를 표시한다',async()=>{const calls:string[]=[];api.get=async(path:string)=>{calls.push(path);return {...detail,reference_photos:[{reference_id:'b',photo:{url:'/api/media/protected-b',source_kind:'ai_generated_demo'}},{reference_id:'unrelated',photo:{url:'/api/media/unrelated',source_kind:'ai_generated_demo'}},{reference_id:'a',photo:{url:'/api/media/protected-a',source_kind:'user_upload'}}]} as any;};render(h(Session.Provider,{value:account as any},h(SubmissionDetail,{id:'s1'})));await screen.findByAltText('적용 Reference 첫 예시');assert.deepEqual(screen.getAllByAltText(/^적용 Reference/).map(el=>el.getAttribute('src')),['/api/media/protected-a','/api/media/protected-b']);assert.equal(screen.getAllByText('AI 생성 시연 이미지').length,1);assert.deepEqual(calls,['/submissions/s1']);});
test('MEDIA-CLARIFY-1: metadata 누락시 원래 photo_id URL만 사용하고 출처를 만들지 않는다',async()=>{api.get=async()=>detail as any;render(h(Session.Provider,{value:account as any},h(SubmissionDetail,{id:'s1'})));await screen.findByAltText('적용 Reference 첫 예시');assert.deepEqual(screen.getAllByAltText(/^적용 Reference/).map(el=>el.getAttribute('src')),['/api/media/old-a','/api/media/old-b']);assert.equal(screen.queryByText('AI 생성 시연 이미지'),null);});
