import {useEffect,useId,useState,useRef,type ReactNode,type FormEvent} from 'react';
import {Link,useLocation,useSearchParams} from 'react-router-dom';
import {ApiError,useData,useAction,useSession,type Row,type Rows,queryString,api} from './data';
import {rate,validatePhotos} from './rules';
export {rate};
export const label:Record<string,string>={reference:'분석에 적용한 Reference',queued:'대기 중',running:'분석 중',succeeded:'분석 완료',failed:'기술 실패',pass:'준수',fail:'개선 필요',unknown:'판단 불가',open:'확인 대기',in_progress:'조치 중',resolved:'해결',normal:'보통',high:'높음',low:'낮음',medium:'중간',store_owner:'점주',ofc:'OFC',regional:'지역 관리자',hq:'본사',platform_operator:'플랫폼 운영자',not_submitted:'미제출',needs_attention:'조치 확인',processing:'분석 중',technical_failure:'기술 실패',unassessable:'OFC 확인 필요',evaluated:'평가 완료',available:'정상',unavailable:'연결 확인 필요',healthy:'정상',stale:'최근 응답 없음',ready:'연결 완료',missing:'연결 누락',invalid:'연결 점검',info:'안내',maintenance:'점검',similar:'유사',different:'차이 있음',HQ:'본사',REGION:'지역',STORE:'매장',CATEGORY:'매대',real_ai:'실제 AI 분석',mock:'Mock 데이터',ai_generated_demo:'AI 생성 시연 이미지',user_upload:'제출 사진',seed_demo:'AI 생성 시연 이미지',resolved_change:'개선 완료',unchanged:'동일',regressed:'추가 개선 필요'};
export const text=(v:unknown)=>v==null?'—':label[String(v)]??String(v);
export const date=(v:string|null|undefined)=>v?new Date(v).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'})+' KST':'—';
export function Tag({value}:{value:string}){return <span className={`tag tag-${value}`}>{text(value)}</span>;}
export function Heading({eyebrow,title,children}:{eyebrow?:string;title:string;children?:ReactNode}){return <header className="page-title"><small>{eyebrow??'현장 포켓'}</small><h1 tabIndex={-1}>{title}</h1>{children&&<p>{children}</p>}</header>;}
export function Card({children,className=''}:{children:ReactNode;className?:string}){return <section className={'card '+className}>{children}</section>;}
export function Empty({children='조건에 맞는 항목이 없습니다.'}:{children?:ReactNode}){return <div className="empty"><span aria-hidden="true">○</span><p>{children}</p></div>;}
export function ErrorBox({error,retry}:{error:Error|null;retry?:()=>void}){if(!error)return null;return <div className="error" role="alert"><strong>{error.message}</strong>{error instanceof ApiError&&error.details?.map((d,i)=><p key={i}>{d.message}</p>)}{error instanceof ApiError&&error.status===409&&<p>최신 정보를 확인한 뒤 입력한 내용을 다시 적용해 주세요.</p>}{error instanceof ApiError&&error.requestId&&<small>문의 번호 {error.requestId}</small>}{retry&&<button type="button" onClick={retry}>상태를 다시 확인</button>}</div>;}
export function DataState({state,children}:{state:{data:any;error:Error|null;loading:boolean;reload:()=>void};children:ReactNode}){if(state.error)return <ErrorBox error={state.error} retry={state.reload}/>;if(state.loading&&!state.data)return <div className="loading" role="status">잠시만 기다려 주세요…</div>;return <>{children}</>;}
export function Field({label:caption,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="field"><span>{caption}</span>{children}{hint&&<small>{hint}</small>}</label>;}
export function Photo({photo,title}:{photo:Row;title?:string}){const [error,setError]=useState(false);return <figure className="photo">{error?<button type="button" onClick={()=>setError(false)}>사진 다시 보기</button>:<img src={photo.url} alt={title??`제출 사진 ${photo.position??''}`} onError={()=>setError(true)}/>}<figcaption>{title??`사진 ${photo.position??''}`} {photo.source_kind&&<Tag value={photo.source_kind}/>}</figcaption></figure>;}
export function Pagination({data}:{data:Rows|null}){const [q,setQ]=useSearchParams();if(!data||data.total<=data.page_size)return null;const move=(page:number)=>{const p=new URLSearchParams(q);p.set('page',String(page));setQ(p);};return <nav className="pagination" aria-label="목록 페이지"><button disabled={data.page<=1} onClick={()=>move(data.page-1)}>이전</button><span>{data.page} / {Math.ceil(data.total/data.page_size)} · {data.total}건</span><button disabled={data.page*data.page_size>=data.total} onClick={()=>move(data.page+1)}>다음</button></nav>;}
export function useListPath(path:string,allowed:string[]=[]){const [q]=useSearchParams();const p=new URLSearchParams();['page','page_size',...allowed].forEach(k=>{const v=q.get(k);if(v)p.set(k,v);});return path+(p.size?'?'+p.toString():'');}
export function Filters({business=false,dates=true,fields=[]}:{business?:boolean;dates?:boolean;fields?:{name:string;title:string;type?:string;options?:{id:string;name:string}[]}[]}){const [q,setQ]=useSearchParams();const {account}=useSession();const regions=useData<Rows>(business&&account.role!=='store_owner'?'/regions?page_size=100':null);const stores=useData<Rows>(business?'/stores?page_size=100':null),categories=useData<Rows>(business?'/categories?page_size=100':null);const all:{name:string;title:string;type?:string;options?:Row[]}[]=[...(business&&account.role!=='store_owner'?[{name:'region_id',title:'지역',options:regions.data?.items??[]}]:[]),...(business?[{name:'store_id',title:'매장',options:stores.data?.items??[]},{name:'category_id',title:'카테고리',options:categories.data?.items??[]},...(dates?[{name:'date_from',title:'시작일 (UTC)',type:'date'},{name:'date_to',title:'종료일 (UTC)',type:'date'}]:[])]:[]),...fields];return <details className="filters"><summary>조회 조건 {q.size>0&&<span>· 적용 중</span>}</summary><form className="form-grid" key={q.toString()} onSubmit={e=>{e.preventDefault();const p=new URLSearchParams(q);new FormData(e.currentTarget).forEach((v,k)=>{String(v)?p.set(k,String(v)):p.delete(k);});if(p.get('status'))p.delete('unresolved');p.delete('page');setQ(p);}}>{all.map(f=><Field key={f.name} label={f.title}>{f.options?<select name={f.name} defaultValue={q.get(f.name)??''}><option value="">전체</option>{f.options.map((r:Row)=><option key={r.id} value={r.id}>{r.name}</option>)}</select>:<input name={f.name} type={f.type??'text'} defaultValue={q.get(f.name)??''}/>}</Field>)}<div className="actions"><button>조건 적용</button><button type="button" className="secondary" onClick={()=>setQ({})}>초기화</button></div></form></details>;}
export const businessKeys=['store_id','region_id','category_id','date_from','date_to','is_active'];
export function SubmissionCard({item,prefix}:{item:Row;prefix:string}){const location=useLocation();return <Link className="submission-card" to={`${prefix}/submissions/${item.id}${location.search}`}><div className="thumb">{item.thumbnail&&<img src={item.thumbnail.thumbnail_url} alt={`${item.category_name} 제출 사진`}/>}</div><div><small>{date(item.created_at)} {item.parent_submission_id?'· 다시 제출':''}</small><h3>{item.store_name} · {item.category_name}</h3><Tag value={item.job.status}/>{item.review_summary&&<span className="score-line">준수 {rate(item.review_summary.compliance_rate)} · 판단 가능 {rate(item.review_summary.assessable_rate)} <Tag value={item.review_summary.source_kind}/></span>}<span className="quiet">{item.open_issue_count?`확인할 조치 ${item.open_issue_count}건`:'내용 확인하기'} →</span></div></Link>;}
export function MutationForm({children,onSave,onDone,onConflict,button='변경 저장',confirm=false,summary='변경 후 현재 권한과 연결 정보에 바로 반영됩니다.',className=''}:{children:ReactNode;onSave:(data:FormData)=>Promise<any>;onDone?:(value:any)=>void;onConflict?:()=>void;button?:string;confirm?:boolean;summary?:string;className?:string}){const action=useAction();const [pending,setPending]=useState<FormData|null>(null);const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const values=new FormData(form);if(confirm&&!pending){setPending(values);return;}void action.run(()=>onSave(pending??values),v=>{setPending(null);form.querySelectorAll<HTMLInputElement>('input[type=password]').forEach(input=>input.value='');onDone?.(v);});};return <form className={'form-grid '+className} onSubmit={submit} onChange={()=>pending&&setPending(null)}>{children}{pending&&<div className="confirm"><strong>변경 내용을 확인해 주세요</strong><p>{summary}</p><p>사유: {String(pending.get('reason')??'입력한 내용으로 저장합니다.')}</p><button type="button" className="secondary" onClick={()=>setPending(null)}>입력으로 돌아가기</button></div>}<ErrorBox error={action.error} retry={action.error instanceof ApiError&&action.error.status===409?onConflict:undefined}/>{action.success&&<p className="success" role="status">{action.success}</p>}<button disabled={action.busy}>{action.busy?'저장 중…':confirm&&!pending?'내용 확인':button}</button></form>;}
export const values=(data:FormData):Row=>Object.fromEntries([...data.entries()].filter(([,v])=>typeof v==='string'));
export const nullValue=(v:unknown)=>v===''||v==null?null:v;
export function Reason(){return <Field label="변경 사유"><textarea name="reason" required maxLength={500} placeholder="어떤 이유로 변경하나요?"/></Field>;}
export function SelectRows({name,rows,value,required=false,blank='선택해 주세요'}:{name:string;rows:Row[];value?:string;required?:boolean;blank?:string}){return <select name={name} defaultValue={value??''} required={required}><option value="">{blank}</option>{rows.map(r=><option key={r.id} value={r.id}>{r.name??r.display_name??r.title}</option>)}</select>;}
export function Notifications({prefix}:{prefix:string}){const s=useData<Rows&{unread_count:number}>(useListPath('/notifications',['unread_only']));const action=useAction();return <><Heading title="알림">현장과 연결된 새 소식을 확인하세요.</Heading><Filters fields={[{name:'unread_only',title:'읽음 상태',options:[{id:'true',name:'읽지 않은 알림'}]}]}/><ErrorBox error={action.error}/><DataState state={s}>{s.data&&!s.data.items.length&&<Empty>새로운 알림이 없습니다.</Empty>}<div className="stack">{s.data?.items.map(n=><Card key={n.id}><small>{date(n.created_at)}</small><h2>{n.title}</h2><div className="actions"><Link className="button" to={`${prefix}/${n.target.type==='issue'?'issues':'submissions'}/${n.target.id}`}>내용 확인</Link>{!n.read_at&&<button className="secondary" disabled={action.busy} onClick={()=>action.run(()=>api.post(`/notifications/${n.id}/read`),s.reload)}>읽음 표시</button>}</div></Card>)}</div><Pagination data={s.data}/></DataState></>;}

export function UploadField({label:caption,required=false}:{label:string;required?:boolean}){const input=useRef<HTMLInputElement>(null);const [selected,setSelected]=useState<File|null>(null);const [url,setUrl]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);useEffect(()=>{if(!selected){setUrl(null);return;}const value=URL.createObjectURL(selected);setUrl(value);return()=>URL.revokeObjectURL(value);},[selected]);return <div><Field label={caption} hint="JPG·PNG, 한 장당 최대 10MB"><input ref={input} name="photo" type="file" accept="image/jpeg,image/png" required={required} onChange={e=>{const file=e.target.files?.[0]??null;const issue=file?validatePhotos([file]):null;setError(issue);setSelected(issue?null:file);if(issue)e.target.value='';}}/></Field>{error&&<p role="alert" className="error">{error}</p>}{selected&&url&&<figure className="photo upload-preview"><img src={url} alt="선택한 Reference 사진 미리보기"/><figcaption>{selected.name} · {(selected.size/1024/1024).toFixed(1)}MB</figcaption><button type="button" className="secondary" onClick={()=>{setSelected(null);if(input.current)input.current.value='';}}>선택한 사진 삭제</button></figure>}</div>;}
